micronaut-projects/micronaut-core

cli/src/main/groovy/io/micronaut/cli/MicronautCli.groovy

Now that we support several languages, it can be misleading to display the Groovy version, as folks might think that Groovy will be included.

Don't display Groovy version

---

src/main/docs/guide/httpServer/staticResources.adoc

Update documentation on static resources to clarify that the router item should not be nested under any other item in the YAML file.

Update documentation on static resources

---

src/main/docs/guide/cli/createProject.adoc

Kotlin app should be named `my-kotlin-app` and not my-groovy-app`

rename of kotlin project name to include kotlin

---

router/src/main/java/io/micronaut/web/router/AnnotatedMethodRouteBuilder.java
router/src/main/java/io/micronaut/web/router/RouteBuilder.java
router/src/test/groovy/io/micronaut/context/router/AnnotationRouteBuilderAbsoluteAndRelativePathsSpec.groovy

Fixes #265 regarding controller and action URIs concatenation.
This doesn't fix the trailing slash URI, meaning that with `@Get("/some")`, `http://localhost/some` works but `http://localhost/some/` doesn't. According to [RFC 3986](https://tools.ietf.org/html/rfc3986#section-6.2.4) the former should redirect to the latter, but it's just a recommendation and it's not clear that this should be done when implementing a RESTful API.

Fix URI route concatenation

---

src/main/docs/guide/quickStart/buildCLI.adoc

This is the URL shown by GitHub to anon users.

Use https GitHub link in cloning instructions

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/CreateAppCommand.groovy

when either calling `create-app` with a feature or flag with less than 2
chars, a RuntimeException was raised:
`Error occurred running Micronaut CLI: String index out of range: 2`.
The cli tries to give hints when misspelling flags or features, but this
only worked, when at least 2 chars where given. E.g.
`mn create-app foo -f groovy` and
`mn create-app foo -features g` both resulted in an error.

prevent String index out of range error

---

http-client/src/main/java/io/micronaut/http/client/exceptions/HttpClientResponseException.java
http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy

A HttpClientResponseException is thrown when a HttpClient makes a call to a server and the server returns an error (a 400 for instance). However, when the server returns some message as part of the body the exception prints null in the console. That makes very difficult to debug those requests without enabling TRACE log level.
When the response's body is not empty but it cannot be converted to JsonError the method getMessage() get a JsonError with a null message. So instead of printing the exception message it prints null.
This PR fixes that by checking if the JsonError's message is null and in that case it prints the exception's message instead.
A better solution could be to modify FullNettyClientHttpResponse to return an empty Optional in this case instead of returning a new JSONError …

HttpClientResponseException prints null when the body cannot be converted to JSONError

---

cli/src/main/groovy/io/micronaut/cli/io/support/GradleBuildTokens.groovy
cli/src/main/groovy/io/micronaut/cli/io/support/MavenBuildTokens.groovy
cli/src/main/groovy/io/micronaut/cli/profile/AbstractProfile.groovy
cli/src/main/groovy/io/micronaut/cli/profile/DefaultFeature.groovy
cli/src/main/groovy/io/micronaut/cli/profile/Feature.groovy
cli/src/main/groovy/io/micronaut/cli/profile/Profile.java

This change allows profiles and features to specify JVM arguments (necessary to add support for Java agents - e.g. spring-loaded (#228)).

Added support for jvmArgs token in CLI

---

http-server-netty/build.gradle
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyRequestArgumentSatisfier.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server/build.gradle
http-server/src/main/java/io/micronaut/http/server/binding/RequestArgumentSatisfier.java

Pulled up RequestArgumentSatisfier to `http-server` module to simplify the creation of own http server implementation #367. to achieve this `http-server` now depends also on `routes`. other option would be to create a separate module just for the satisfier which doesn't make much sense to me as router seems crucial for the HTTP server anyway. I'm not sure about the `shadowJar` settings in `http-server` after adding `router` dependency

pulled up RequestArgumentSatisfier to http-server module #367

---

http-client/src/main/java/io/micronaut/http/client/NettyClientHttpRequest.java
http/src/main/java/io/micronaut/http/HttpRequest.java
http/src/main/java/io/micronaut/http/HttpRequestFactory.java
http/src/main/java/io/micronaut/http/HttpResponseFactory.java
http/src/main/java/io/micronaut/http/cookie/CookieFactory.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpParameters.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpRequest.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpRequestFactory.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpResponse.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpResponseFactory.java
http/src/main/java/io/micronaut/http/simple/cookies/SimpleCookie.java
http/src/main/java/io/micronaut/http/simple/cookies/SimpleCookieFactory.java
http/src/main/java/io/micronaut/http/simple/cookies/SimpleCookies.java
http/src/main/java/io/micronaut/http/simple/cookies/package-info.java
http/src/main/java/io/micronaut/http/simple/package-info.java

This is a default fallback implementation of `Cookie`, `HttpRequest` and `HttpResponse` if Netty implementation is not on the classpath. This is particularly useful for very simple unit tests and custom HTTP server implementations #367.

default simple implementation for http request and response

---

travis-build.sh

When TRAVIS_TAG, update the `static-website` file `releases.yml`
https://github.com/micronaut-projects/static-website/blob/master/main/src/main/resources/releases.yml
via this script: 
https://github.com/micronaut-projects/static-website/blob/master/release.sh

when release, update static-website

---

http-client/src/main/java/io/micronaut/http/client/NettyClientHttpRequest.java
http-netty/src/main/java/io/micronaut/http/netty/NettyHttpParameters.java
http/src/main/java/io/micronaut/http/MutableHttpParameters.java
http/src/main/java/io/micronaut/http/MutableHttpRequest.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpHeaders.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpParameters.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpRequest.java

This makes `MutableHttpRequest` _more mutable_
Additional changes requried for the custom HTTP server implementation:
* exposed `SimpleHttpHeaders` to implementing classes
* added constructors for `SimpleHttpHeaders` and `SimpleHttpParameters`
which accepts the original mutable map

mutable http parameters for mutable http request

---

src/main/docs/guide/httpServer/serverConfiguration/cors.adoc

There is a typo in `Allowed Methods` section

Change 'allowedHeaders' to 'allowedMethods'

---

src/main/docs/guide/commandLineApps/picocli/picocliGenerateProject.adoc

Remove `example` param as there was already a name

Remove wrong create-app params

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/HttpResponseSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/java/ResponseController.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/StaticResourceResolutionSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/FileTypeHandlerSpec.groovy
http/src/main/java/io/micronaut/http/HttpResponse.java

- Added support for `location` URI header to be added to `HTTP 202 - ACCEPTED` response
- Fixed some unit tests which were failing due to last modified date comparison
Closes #532

HttpResponse - HTTP 202 Accepted (URI location)

---

src/main/docs/guide/configurations/dataAccess/mongoSupport.adoc

Add a note instructing how to specify the database when using
GORM for MongoDB.  It has to be specified in the
`grails.mongodb.databaseName` property instead of the
expected `mongodb.uri` property.

GORM for MongoDB database name

---

http/src/main/java/io/micronaut/http/HttpResponse.java

Fixed a documentation bug, and added a new method for server error allowing a user to pass a body

Add an overloaded serverError method accepting a body

---

http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
http-client/src/test/groovy/io/micronaut/http/client/ClientIntroductionAdviceSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/aop/HateosCrudSpec.groovy

Fixes #581
Also the handling of consumes/produces was backwards in the client advice. Consumes was being used to set the content type and Produces to set the accept header.

Fix client introduction advice issues

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/render/AccessRefreshToken.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/render/AccessRefreshTokenSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/render/BearerAccessRefreshTokenSpec.groovy

accessToken and refreshToken were camel case and did not use
underscores. Example in docs as well and RFC show it with underscore.
As well tooling (Postman) expects it to be underscore.
#607

Fix issue with oauth response not being 100% compliant

---

test-suite/src/test/groovy/io/micronaut/docs/server/intro/HelloController.java

Default Micronaut configuration produces application/json. So if you run the example in a browser (rather than curl), you can get an error page about invalid JSON (like on Firefox 63).

text/plain media type on HelloController

---

http-client/src/test/groovy/io/micronaut/http/client/JsonStreamSpec.groovy
http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonHttpContentSubscriberFactory.java

With asynchronous request handling.
The test is a little funny, with the semaphore to ensure that the sending and receiving really happens concurrently. That could be taken out.

Allow JSON streaming in the body of a HTTP request

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/JsonStreamSpec.groovy

Subject says it all -- when I added a test through a @Client (for completeness), it didn't match the controller's URI. Turns out there's an short-circuit return in the middle of io.micronaut.http.client.DefaultHttpClient#buildNettyRequest so it doesn't set the (file part of) the requestURI.
This took one me forever to hunt down, through umpteen publishers of request URIs, requests and whatnot... :-)

Include base URI from @Client(uri="...") in request line for streamed request body

---

build-projects/asciidoc-config-props/src/main/groovy/io/micronaut/documentation/asciidoc/AsciiDocPropertyReferenceWriter.java

With this change it is possible to render correctly config properties like `micronaut.caches.*.redis.caches.*.server`

Fix render more than one * asciidoc in config properties

---

http-client/src/test/groovy/io/micronaut/http/client/aop/StreamSpec.groovy
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java

This refines the framing of JSON content by discriminating between payloads that are likely to be JSON formatted (such as beans handled by Jackson), and String og byte-ish constructs, ready for the Netty layer.

Fixes #734 by examining the Java payload inside the streaming container.

---

configurations/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/JpaConfiguration.java

As discussed on Gitter added `getProperties()` to `JpaConfiguration`.
This way properties can be added in e.g. a `BeanCreatedEventListener<JpaConfiguration>` bean event.

Added (missing) getProperties method to JpaConfiguration

---

configurations/aws-common/src/main/java/io/micronaut/configuration/aws/EnvironmentAWSCredentialsProvider.java
configurations/aws-common/src/test/groovy/io/micronaut/configuration/aws/EnvironmentAWSCredentialsProviderTest.groovy
configurations/aws-common/src/test/resources/application.yml

AWS credentials: accessKeyId, accessKey, secretKey, secretAccessKey, and sessionToken were not being resolved using camel case env variable names.  I was only able to access them using hyphenated format.
From the Micronaut documentation it seems that variables can't be accessed using camel case:  https://docs.micronaut.io/latest/guide/index.html#environments

AWS environment variables were not being resolved using camel case format

---

src/main/docs/guide/cloud/serviceDiscovery/serviceDiscoveryManual.adoc

Fixed typo in default health check path.

Fix typo in documentation

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieConfigurationProperties.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/cookie/JwtCookieLoginHandler.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookiePathSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/LoginForm.groovy

Fixes #798 
I wanted to set the default cookie path to / but that would alter the current behavior. But I think the current behavior is wrong. Discuss.

Make JWT cookie path configurable

---

src/main/docs/guide/languageSupport/graal.adoc
src/main/docs/guide/languageSupport/graal/graalServices.adoc

Now that Graal-RC7 is back in SDKMan and old releases won't be removed, at least until Graal 1.0 GA, we can also create native images without using Docker. This PR updates the documentation to explain users both options and also document how to build the image using Graal-RC8.
This needs to be merged with: https://github.com/micronaut-projects/micronaut-profiles/pull/84

Graal improvements

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/DataStreamSpec.groovy
http/src/main/java/io/micronaut/http/HttpResponseWrapper.java

1. Call the streaming DefaultHttpClient.exchangeStream()
2. Drain the published info into temporary storage (e.g. by blockingIterable, buffer, etc.), or consume them in an asynchronous fashion.
3. See that the bodies are mixed up
Each returned result from the Flowable should be independent from the others
Each returned result from the Flowable is the same object, but the contained body is exchanged between each "next".
- **Operating System**: All
- **Micronaut Version:** 1.0.0
- **JDK Version:** All
Added as an instructive test case in `io.micronaut.http.client.DataStreamSpec#test that stream response is free of race conditions`. Without the fix, this happens:
```
Condition not satisfied:
new String(arrays[0]) == 'The Stand'
|          |     |    |
The Shining|     |    false
|     |    5 …
```

Wrapping of different body-payloads in same response object in reactive stream [1.0.x]

---

configurations/redis-lettuce/src/test/groovy/io/micronaut/configuration/lettuce/session/RedisSessionSpec.groovy
session/src/main/java/io/micronaut/session/http/HttpSessionConfiguration.java

This is technically a breaking change since the visibility of the API is changing, however it isn't possible for any users to extend the API and have it work since they wouldn't be creating apps with the `io.micronaut` package.

Redis session configuration fix

---

security-session/src/main/java/io/micronaut/security/session/SessionAuthenticationFetcher.java
security-session/src/main/java/io/micronaut/security/session/SessionLoginHandler.java
security/src/main/java/io/micronaut/security/authentication/DefaultAuthentication.java
security/src/main/java/io/micronaut/security/authentication/PrincipalArgumentBinder.java
security/src/main/java/io/micronaut/security/authentication/jackson/SecurityJacksonModule.java

The initial concern is that the UserDetails object was being put into the session. Given that the default implementation is in memory, and the only external implementation didn't work, I think the risk of causing issues with existing session data is low. The only way that would happen is if the user implemented their own external session store that uses serialization.

Resolve issue with security-session putting user details in the session

---

inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java

New and bigger AWS EC2 instances no longer provide file
`/sys/hypervisor/uuid` that was previously used as a ec2 autodetection
mechanism; this PR adds reading of `/sys/devices/virtual/dmi/id/bios_vendor`
file to enhance aws ec2 autodetection.
Fixes #914

Improve AWS EC2 autodetection

---

http-client/src/test/groovy/io/micronaut/http/client/HostHeaderSpec.groovy

Tackling #920 
For now just implemented a "naive" check for `Linux` to see if that does the trick for Travis too.
Btw does this test currently pass on `MacOS` ?

Ignore tests on reserved ports for Linux

---

spring/src/test/groovy/io/micronaut/spring/tx/EventListenerSpec.groovy
spring/src/test/groovy/io/micronaut/spring/tx/FakeEvent.groovy
spring/src/test/groovy/io/micronaut/spring/tx/TransactionalListener.java

Tackling #919 and now `EventListenerSpec` is agnostic of `StartupEvent` by making it rely on a custom event instead.

Fixing EventListenerSpec

---

router/src/main/java/io/micronaut/web/router/AnnotatedMethodRouteBuilder.java

Pass the bean and method directly to avoid conflicts with multiple beans extending a base class that contains the method.

Annotated route builder changes

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/ExpirationJwtClaimsValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/GenericJwtClaimsValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/SubjectNotNullJwtClaimsValidator.java

Note, this is not a breaking change. JWTValidator only had a public method. 
https://github.com/micronaut-projects/micronaut-core/blob/1.0.x/security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
`    public Publisher<Authentication> validateToken(String token) {`
which is still in place. 
This PR adds a couple of public methods: 
`    public Optional<Authentication> authenticationIfValidJwtSignatureAndClaims(String token, Collection<? extends JwtClaimsValidator> claimsValidators)`
and:
` public Optional<JWT> validateJwtSignatureAndClaims(String token, Collection<? extends JwtClaimsValidator> claimsValidators) {`
which can be used to validate a particular JWT which needs extra Claims validations. For example, in an Open ID connect ID Token validation
I …

Add more functionality to JwtTokenValidator

---

inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java

Closes https://github.com/micronaut-projects/micronaut-test/issues/5
Original issue: https://github.com/redhat-developer/vscode-java/issues/693
Workarround until https://bugs.eclipse.org/bugs/show_bug.cgi?id=541466 is fixed.
This should work for any JVM based language since I fixed it in `inject` directly instead of `inject-java`.
It will ignore `org.eclipse.jdt.internal.compiler.problem.AbortCompilation` for all anotations while building the metadata and let other exceptions pass.
from @graemerocher reproduction in original issue
With VS code and [Java Extension Pack](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack) extension installed
* Clone the repo https://github.com/micronaut-projects/micronaut-examples
* cd hello-world-java
* Remove the build.gradle (so …

Fix compilation issue with Eclipse APT implementation

---

src/main/docs/guide/appendix/usingsnapshots.adoc

- lead users to guess the correct snapshot version
- it might make sense to have this section automatically
updated whenever a new release is made
Fixes #992

update documentation about snapshot versions

---

router/src/main/java/io/micronaut/web/router/DefaultFilterRoute.java

if the URI is absolute then the filter won' match

using path for matching filters instead of URI.toString()

---

validation/src/main/java/io/micronaut/validation/exceptions/ConstraintExceptionHandler.java
validation/src/test/groovy/io/micronaut/validation/Pojo.java
validation/src/test/groovy/io/micronaut/validation/ValidatedSpec.groovy

This PR fix some but not all of the issues described in https://github.com/micronaut-projects/micronaut-core/issues/980
- Remove extra dot after property paths. This issue is only visible (in 1.0.1) when there are multiple violations.
- Change extra nested "_embedded" key to "errors". I'm not sure if this can be fixed on the 1.0.x branch as it alters the JSON response. I hope no one depends on the wrong structure in 1.0.1.

Fix issues with multiple validation errors response

---

src/main/docs/guide/httpServer/views/freemarker.adoc
src/main/docs/guide/toc.yml
views/build.gradle
views/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRenderer.java
views/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRendererConfiguration.java
views/src/main/java/io/micronaut/views/freemarker/FreemarkerViewsRendererConfigurationProperties.java
views/src/main/java/io/micronaut/views/freemarker/package-info.java
views/src/test/groovy/io/micronaut/docs/FreemarkerController.groovy
views/src/test/groovy/io/micronaut/docs/FreemarkerViewRendererSpec.groovy
views/src/test/groovy/io/micronaut/docs/HandlebarsViewsRendererSpec.groovy
views/src/test/groovy/io/micronaut/docs/ThymeleafViewRendererSpec.groovy
views/src/test/groovy/io/micronaut/docs/ViewsFilterSpec.groovy
views/src/test/resources/views/home.ftl

"Inspired" in the Velocity view implementation, add support for Freemarker.
All configuration defined by Freemarker is supported in the Micronaut configuration.
As another view, the same kind of tests and documentation are created.

Add support to Freemarker views

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/AbstractCreateCommand.groovy

mn create-app does not support application names with underscores it does support dashes.

Minor error message change, create-app supports dashes not underscores.

---

discovery-client/src/main/java/io/micronaut/discovery/eureka/EurekaConfiguration.java
discovery-client/src/main/java/io/micronaut/discovery/spring/Constants.java
discovery-client/src/main/java/io/micronaut/discovery/spring/SpringCloudConfiguration.java
discovery-client/src/main/java/io/micronaut/discovery/spring/condition/RequiresSpringCloudConfig.java
discovery-client/src/main/java/io/micronaut/discovery/spring/condition/package-info.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/SpringCloudConfigConfigurationClient.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/AbstractSpringCloudConfigClient.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/SpringCloudConfigClient.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/SpringCloudConfigOperations.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/package-info.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/response/ConfigServerPropertySource.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/client/response/ConfigServerResponse.java
discovery-client/src/main/java/io/micronaut/discovery/spring/config/package-info.java
discovery-client/src/main/java/io/micronaut/discovery/spring/package-info.java

This is the pull request related to the issue #501, to include the configuration client for Spring Cloud config client.

Spring Cloud config server client

---

router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
router/src/test/groovy/io/micronaut/web/router/version/DefaultVersionedUrlFilterSpec.groovy

Found an issue in `RouteVersionFilter` with resolving strategies processing
This cleanup commit makes this bug more visible in code: https://github.com/micronaut-projects/micronaut-core/commit/f3432dfd9e9ba8b7f826b35a893ff69b0bf629b6
Description:
If the first resolving strategy in `resolvingStrategies` will return `Optional.empty()`
`opt.map(...).orElse(true)` will return `true` and `anyMatch` will return `true` immedialty.
A test case provided with this logic fixed.
Without the fix the test returns `matches.size() == 4` and is incorrect.

Only first resolving strategy usage for route filtering fix

---

src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationConsul.adoc

Update the documentation with the correct FILE (not FILES) setting for consul.client.config.format.

Documentation error for consul.client.config.format: FILE

---

inject-java/src/test/groovy/io/micronaut/inject/close/A.java
inject-java/src/test/groovy/io/micronaut/inject/close/B.java
inject-java/src/test/groovy/io/micronaut/inject/close/BImpl.java
inject-java/src/test/groovy/io/micronaut/inject/close/BeanCloseOrderSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/close/C.java
inject-java/src/test/groovy/io/micronaut/inject/close/D.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

I also noticed there isn't anything in the documentation about how to get a bean to participate in the closing of the context. Simply implementing Closeable or AutoCloseable isn't enough. One must either use the `@Bean(preDestroy =` for a factory bean or annotate a method with `@PreDestroy` for a bean class.

Add topological sorting to beans before closing

---

cli/src/main/groovy/io/micronaut/cli/io/support/FileSystemResource.java
cli/src/main/groovy/io/micronaut/cli/io/support/SpringIOUtils.java
core/src/main/java/io/micronaut/core/io/Streamable.java
core/src/main/java/io/micronaut/core/io/Writable.java
core/src/main/java/io/micronaut/core/io/file/DefaultFileSystemResourceLoader.java
core/src/main/java/io/micronaut/core/io/scan/ClassPathAnnotationScanner.java
inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
inject/src/main/java/io/micronaut/inject/writer/DirectoryClassWriterOutputVisitor.java
inject/src/main/java/io/micronaut/inject/writer/FileBackedGeneratedFile.java

Hello,
[issue 1167](https://github.com/micronaut-projects/micronaut-core/issues/1167) looked like a good first issue.
I replaced the constructor calls with calls to the factory methods. 
Using Path instead of File I left out as this would be a bigger change. To me it also looked like it would result in API breaking changes (for example in io.micronaut.cli.io.support.UrlResource.getFile())

Issue 1167 - FileInputStream / FileOutputStream Considered Harmful

---

security-session/src/main/java/io/micronaut/security/session/SecuritySessionConfigurationProperties.java
security/src/main/java/io/micronaut/security/handlers/ForbiddenRejectionUriProvider.java
security/src/main/java/io/micronaut/security/handlers/RedirectRejectionHandler.java
security/src/main/java/io/micronaut/security/handlers/UnauthorizedRejectionUriProvider.java
security/src/test/groovy/io/micronaut/security/handlers/CustomForbiddenRejectionUriProvider.groovy
security/src/test/groovy/io/micronaut/security/handlers/CustomUnauthorizedRejectionUriProvider.groovy

It maybe useful to provide the current http request to both unauthorized and forbidden redirect uri providers. For example, you may choose to redirect to a url with a parameter containing a cookie value.

Adds HttpRequest to Unauthorized & forbidden

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/claims/JwtClaimsSetAdapter.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/ExpirationJwtClaimsValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JWTClaimsSetUtils.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtClaimsValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/SubjectNotNullJwtClaimsValidator.java

To avoid coupling to the class `JWTClaimsSet` which comes from the dependency used for JWT right now which is Nimbus JOSE+JWT.
Please, note that `JwtTokenValidator.java` does not exist in `1.0.x`

Use a Map in the interface instead of JWTClaimsSet

---

http/src/main/java/io/micronaut/http/codec/MediaTypeCodec.java

This PR fixes a copy/paste issue in the javadocs.

Fix wrong javadoc comments

---

inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java

The problem was that `MongoClient` implements `Closeable`, but the `close()` method implementation is on the superclass.
`TypeElement.getEnclosedElements` "Returns the fields, methods, constructors, and member types that are **directly declared** in this class or interface."  Thus, any `preDestroy` method declared on a superclass or extended interface would be missed.

Handle preDestroy when method defined on superclass.  Fixes #1272

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/render/AccessRefreshToken.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/render/BearerAccessRefreshToken.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/render/BearerTokenRenderer.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/LoginControllerSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/render/AccessRefreshTokenSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/render/BearerAccessRefreshTokenSpec.groovy
src/main/docs/guide/appendix/breaks.adoc

I'm trying to use the [Dart OAuth2 Client](https://pub.dartlang.org/packages/oauth2) to manage authentication with a providing Micronaut server. I'm running into issues when the (respective client attempts to refresh credentials because [there isn't a `token_type` field](https://github.com/dart-lang/oauth2/blob/master/lib/src/handle_access_token_response.dart#L65). It appears that the client expectations [comply with the specification](https://tools.ietf.org/html/rfc6749#section-4.1.4), prompting this PR to adjust the response.
Adding the fields to the `AccessRefreshToken` seemed like a reasonable implementation change to accommodate my clients requirements, let me know if something else would be preferred.
This changes the refresh token response from:
```
{
"access_token": "xxx...", …
```

Expires in and token type properties included in AccessRefreshToken

---

runtime/src/main/java/io/micronaut/cache/CacheConfiguration.java
runtime/src/main/java/io/micronaut/cache/DefaultSyncCache.java

Many cache implementation - like Caffeine - support recording statistics to get cache insights regarding hit/miss ratio's. With these insights the application's caches can be fine tuned / optimised. 
Caffeine has `recrodStats` method to enable recording the statistics.
```
Cache<Key, Graph> graphs = Caffeine.newBuilder()
.maximumSize(10_000)
.recordStats()
.build();
```
This PR adds configuration support for enabling recording statistics of Micronaut caches.

Added cache configuration option to record stats.

---

management/src/main/java/io/micronaut/management/endpoint/beans/BeansEndpoint.java
management/src/main/java/io/micronaut/management/endpoint/beans/impl/DefaultBeanDefinitionData.java
management/src/main/java/io/micronaut/management/endpoint/beans/impl/RxJavaBeanDefinitionDataCollector.java
management/src/main/java/io/micronaut/management/endpoint/loggers/LoggerConfiguration.java
management/src/main/java/io/micronaut/management/endpoint/loggers/impl/DefaultLoggersManager.java
management/src/main/java/io/micronaut/management/endpoint/routes/RoutesEndpoint.java
management/src/main/java/io/micronaut/management/endpoint/routes/impl/RxJavaRouteDataCollector.java

This PR consistently sorts beans, loggers and routes endpoint data by using `LinkedHashMap`s and sorting collections. Fix for #1295.

Sorting of endpoint data (fix for #1295)

---

src/main/docs/guide/serverlessFunctions/writingFunctions.adoc

The feature aws-api-proxy indicated in the documentation doesn't exist. It should be aws-api-proxy as correctly indicated by the mn CLI:
```
Setting micronaut 1.1.0.M2 as default.
codependent@xxxx  ~/git/codependent/github  mn create-app micronaut-aws-lambda-proxy --features aws-api-proxy -l kotlin
Resolving dependencies..
| Warning Feature aws-api-proxy does not exist in the profile service! Possible solutions: aws-api-gateway-graal, aws-api-gateway
```

Changed --features aws-api-proxy for --features aws-api-proxy

---

src/main/docs/guide/httpServer/apiVersioning.adoc

Api versioning example in the document is missing the part which enables versioning
Based on comments in https://github.com/micronaut-projects/micronaut-core/issues/997

Fix inconsistency in documentation describing how to enable api versioning

---

src/main/docs/guide/httpServer/apiVersioning.adoc

The custom version resolution text was pointing to the VersionExtractingStrategy class, which has been renamed and relocated to RequestVersionResolver.

Fix link for implementing custom version resolution

---

inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java

The following PR contains a fix for https://github.com/micronaut-projects/micronaut-core/issues/1309 and makes sure that Micronauts `BeanDefinitionInjectProcessor` in **version 1.0.4** participates on every processing round.
Therefore Micronaut includes e.g. `@Singleton` classes that were generated by other third party annotation processors.
- This PR removes the `executed` flag that made sure the processor runs only in round 1.
- And moves the generation of the `/META-INF/services/io.micronaut.inject.BeanDefinitionReference` to the last processing round.
Fixes https://github.com/micronaut-projects/micronaut-core/issues/1309

BeanDefinitionInjectProcessor works with Mapstruct

---

build.gradle
http-server-netty/build.gradle
http-server-netty/src/main/java/io/micronaut/http/server/netty/EpollAvailabilityCondition.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/EpollEventLoopGroupFactory.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/EventLoopGroupFactory.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/KQueueAvailabilityCondition.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/KQueueEventLoopGroupFactory.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/NioEventLoopGroupFactory.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/AbstractMicronautSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/NettyHttpServerConfigurationSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/nativetransport/LinuxNativeTransportSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/nativetransport/MacNativeTransportSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/nativetransport/NativeTransportController.java

To enable netty server's native transport:
- set 'micronaut.server.netty.use-native-transport' to true in application.yml
- add one of netty's native transport dependency 'netty-transport-native-epoll' or 'netty-transport-native-kqueue' to your classpath.
Epoll.isAvailable() or KQueue.isAvailable() will be checked.
If native transport is not available, NioEventLoopGroup will be used.

Add support for netty server's native transport.

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy
src/main/docs/guide/config/propertySource.adoc

Generate all combinations with `.` and `-` for environment variables. Fixes #1191

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/SimpleControllerSpec.groovy
inject/src/main/java/io/micronaut/context/exceptions/BeanInstantiationException.java

* Updated BeanInstantiationException to store rootBeanDefinition.
* Updated implementation of exceptionCaughtInternal to handle BeanInstantiationException and only look for Error handler when the exception doesn't happen while initializing controller.
* Added tests.

#1376 Fix infinite loop

---

management/src/main/java/io/micronaut/management/endpoint/EndpointEnabledCondition.java

Fix to be able to start native-image application with management. Without this the application fails to start with:
```
No BeanIntrospection found for bean type: class io.micronaut.management.endpoint.EndpointEnabledCondition
12:29:57.372 [main] DEBUG i.m.core.reflect.InstantiationUtils - Tried, but could not instantiate type: class io.micronaut.management.endpoint.EndpointEnabledCondition
java.lang.InstantiationException: Type `io.micronaut.management.endpoint.EndpointEnabledCondition` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
at java.lang.Class.newInstance(DynamicHub.java:699)
at io.micronaut.core.reflect.InstantiationUtils.lambda$tryInstantiate$0(InstantiationUtil …
```

Add @Introspected to EndpoointEnabledCondition

---

graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java

Do not skip Graal type visitor if there is a base reflect.json file. Fixes #1391

---

core/src/main/java/io/micronaut/core/naming/NameUtils.java
validation/src/test/groovy/io/micronaut/validation/properties/MixedCasePropertySpec.groovy

I've added a few more test cases that were missing and fixed the regular expression to property detect `:`

Fix "colon" detection when validating property names. Fixes #1217

---

security/src/main/java/io/micronaut/security/rules/InterceptUrlMapRule.java
security/src/test/groovy/io/micronaut/security/rules/InterceptUrlMapRuleSpec.groovy
src/main/docs/guide/security/securityRule/interceptUrlMap.adoc

This PR fixes #1511 by first trying to find  url rules that **exactly match** the http **request method** and the **uri pattern**. 
If there is no match the code falls back to the original behaviour by finding by uri pattern.

InterceptUrlMapRule by exact match on both method and URI

---

build.gradle

This plugin provides a task to determine which dependencies have updates.
Additionally, the plugin checks for updates to Gradle itself. It has been
configured to disallow release candidates as upgradable versions.
More info available at:
https://github.com/ben-manes/gradle-versions-plugin
#gh-1079

Add gradle-versions-plugin to discover dependencies updates

---

runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java

so that the node can be garbage collected ealier.

JacksonProcessor - Remove array node when streaming

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configuration/Engine.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configuration/GroovyConfigBuilderSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/ModelUtils.java
inject-java/src/test/groovy/io/micronaut/inject/configuration/ConfigurationBuilderSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configuration/Engine.java

In working on #1265 I encountered an IllegalAccessorError caused by the AnnotationProcessor utilizing a private field when a public getter was the preferred accessor. @jameskleeh and I walked through reproducing the error (via the new ConfigurationBuilderSpec) and we were able to solve the bug.

Fixes configBuilder visitor for private fields with public getters

---

discovery-client/src/main/java/io/micronaut/discovery/client/DiscoveryClientCacheConfiguration.java
http-client/src/main/java/io/micronaut/http/client/ServiceHttpClientConfiguration.java
http-client/src/test/groovy/io/micronaut/http/client/services/ManualHttpServiceDefinitionSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/ConfigurationPropertiesInheritanceSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/ParentEachProps.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/inheritance/ParentEachPropsCtor.java
inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
runtime/src/main/java/io/micronaut/cache/DefaultSyncCache.java

This PR resolves a couple issues
1. It is not possible to retrieve inner configuration properties of `@EachProperty` as beans directly
2. It is not possible to inject the inner configuration instance into the parent `@EachProperty` constructor

Allow inner configuration properties of @EachProperty to be singletons

---

inject-java/src/test/groovy/io/micronaut/inject/factory/nullreturn/FactoryConstructor.java
inject-java/src/test/groovy/io/micronaut/inject/factory/nullreturn/NullReturnFactorySpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/factory/nullreturn/NullableFactory.java
inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

This PR is not supporting Optional for a several reasons
1. It would no longer be possible to create beans of type `Optional` in a factory (unlikely I'm aware)
2. It would require changes to byte code generation for the bean definitions to set the bean type to the generic
3. It would require additional logic in many places to unwrap the optional anytime a bean is retrieved
4. Optional is really meant for an API the user will call. Factory methods should never be called directly so there is no benefit other than satisfying a feature that users may expect to work

Allow factory methods to return null

---

inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
runtime/src/main/java/io/micronaut/scheduling/processor/ScheduledMethodProcessor.java
runtime/src/test/groovy/io/micronaut/scheduling/ScheduledFixedRateSpec.groovy
src/main/docs/guide/aop/scheduling.adoc
test-suite/src/test/groovy/io/micronaut/docs/aop/scheduled/ScheduledExample.java

This technically has an improvement, which is adding support for only specifying an `initialDelay` in the scheduled annotation.
What could be considered a breaking change is throwing an exception when the task could not be scheduled due to no configuration ie just `@Scheduled` on the method with no members. I think its incorrect behavior to simply ignore the annotation in that case.

Scheduled issues

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java

Reuse handlers that are Sharable (https://netty.io/4.1/api/io/netty/channel/ChannelHandler.Sharable.html)
I think HttpResponseEncoder and RoutingInBoundHandler can also be annotated with @Sharable.

Reuse sharable netty's handlers.

---

http/src/main/java/io/micronaut/http/MediaType.java
http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy

As per [rfc2045 Syntax of the Content-Type Header Field](https://tools.ietf.org/html/rfc2045#section-5.1):
```
In the Augmented BNF notation of RFC 822, a Content-Type header field
value is defined as follows:
content := "Content-Type" ":" type "/" subtype
*(";" parameter)
; Matching of media type and subtype
; is ALWAYS case-insensitive.
```

Changing equals method to be case insensitive as per rfc2045

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/ProfileInfoCommand.groovy

Fix the padding for the `profile-info` command on the CLI.
On the right the current oputput, on the left the one after applying this PR:

Fix profile-info padding

---

test-suite-kotlin/src/test/kotlin/io/micronaut/docs/context/annotation/primary/Green.kt

Added missing `end::clazz[]` tag.

Updated Green.kt for multi-lingual docs

---

src/main/docs/resources/css/custom.css

When viewing documentation on a mobile device, it's helpful to have the documentation as individual pages.
Fortunately this is already available at:
https://docs.micronaut.io/latest/guide/introduction.html
However, it does not render properly.
This PR fixes the rendering.  
A link on the home page to the multipage version would be appreciated.

Improve multipage documentation rendering.

---

src/main/docs/guide/cloud/distributedTracing/jaeger.adoc

I think the Jaeger documentation was created by copying then editing the zipkin doc.  There were a couple places where "zipkin" was not replaced by "jaeger".

Update jaeger.adoc to replace references to zipkin

---

inject/src/main/java/io/micronaut/context/env/AbstractPropertySourceLoader.java
inject/src/main/java/io/micronaut/context/env/ActiveEnvironment.java
inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
inject/src/main/java/io/micronaut/context/env/PropertySourceLoader.java
inject/src/test/groovy/io/micronaut/context/env/EnvironmentOrderSpec.groovy
inject/src/test/resources/application-first.yml
inject/src/test/resources/application-second.yml
management/src/main/java/io/micronaut/management/endpoint/info/source/PropertiesInfoSource.java

Support deterministic ordering of environment property sources
`-Dmicronaut.environments=a,b,c` will result in `c` having the highest precedence.

Environment order

---

inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java

Continuation of #1694. Injected fields and factory methods using types not yet generated were not handled. 
Separate but related note: these two cases are being silently ignored rather than failing with an error, like what happens for constructor parameters. It is probably not a problem as for legitimate cases, the compilation should fail anyway, but it did throw me off until I realised that the fix was incomplete. Some tests were failing with strange errors.
The inject case gets resolved to void in case of an error typemirror and ends up with V.class in the BeanDefinition, leading to a NoClassDefFound for V. I thought I was going insane the first time I saw it. It  is now fixed for the case when the injected field type is generated in a subsequent annotation processing round.
The bean …

fixed delayed resolve error type mirror for @Inject fields and method return types

---

http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
http/src/main/java/io/micronaut/http/HttpAttributes.java

This patch adds MethodInvocationContext to request attributes generated by HttpClientIntroductionAdvice. Primary motivation is to allow HttpClientFilter access executed method metadata, e.g. annotations.

Expose declarative HTTP client MethodInvocationContext

---

inject-java/src/test/groovy/io/micronaut/inject/qualifiers/primary/C.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/primary/C1.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/primary/C2.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/primary/PrimarySpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

I discovered that multiple `@Primary` beans won't create `NonUniqueBeanException` on injection, but they should.

Fix duplicate primary bean handling

---

test-suite-kotlin/src/test/kotlin/io/micronaut/core/beans/RecursiveGenericsSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/core/beans/RecusiveGenericsSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/builder/VehicleSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/factories/VehicleSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/inject/intro/VehicleSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/inject/qualifiers/named/VehicleSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/inject/scope/RefreshEventSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/beans/IntrospectionSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/intro/HelloClientSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/intro/HelloControllerSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/constructor/nullableinjection/ConstructorNullableInjectionSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/field/nullableinjection/FieldNullableInjectionSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/method/nullableinjection/SetterWithNullableSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/property/MapFormatSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/repeatable/RepeatableSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/requires/RequiresSdkSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/visitor/beans/BeanIntrospectorSpec.kt

@willbuck Would you look this over and verify that it all makes sense?  Feel free to add subsequent commits to address any concerns you have.  Note that `RecusiveGenericsSpec.kt` is currently configured with `enabled=false`.  I am not sure why that is failing.  (separate from the typo in the class name)
Thanks for your help!

Updating some tests to use kotlintest

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
http-client/src/test/groovy/io/micronaut/http/client/config/DefaultHttpClientConfigurationSpec.groovy

Add a way to set ProxySelector that can dynamically pick a proxy based on host and port.
- it picks only the first proxy returned by ProxySelector.select method
- it never call ProxySelector.connectFailed
- it does not use default proxy selector as provided by Java. This would potentially be a breaking change, it can be considered for next major release.

Add support for ProxySelector

---

cli/src/main/resources/unixStartScript.txt

Fix hardcoded environment variable name `GRADLE_OPTS` to dynamic variable name `optsEnvironmentVar`.
(The `optsEnironmentVar` will replace to `NM_OPTS`)

Fix env var name from GRADLE_OPTS to optsEnvironmentVar variable (enabled only macOS)

---

cli/src/main/groovy/io/micronaut/cli/io/support/MavenBuildTokens.groovy

See discussion: https://github.com/micronaut-projects/micronaut-profiles/issues/124
This change is required before merging the profiles PR: https://github.com/micronaut-projects/micronaut-profiles/pull/161

Added implemenation scope to Maven build token mappings.

---

src/main/docs/guide/ioc/android.adoc

A concept that is foreign for non-Android devs, is that there are a bunch of entry lifecycle points but no exit lifecycle for the whole _application_ (there is for `Activity` ie. the Android OS interface for creating views). So there is no concept of "exiting application", it just disappears from the heap at some point, the Android OS handles this. As developer you should therefore not rely on cleanup code in the `Application`, only in `Activities` (or similar) - which are also not guaranteed to be called (specifically `onDestroy()`).
In this particular case, this is even worse because `onTerminate()` is _only_ called in emulator environments (check out: https://developer.android.com/reference/android/app/Application.html#onTerminate())
which makes this example highly misleading. As the …

Fix incorrect usage of Androids onTerminate() in doc

---

runtime/src/main/java/io/micronaut/health/HeartbeatDiscoveryClientCondition.java
runtime/src/test/groovy/io/micronaut/health/HeartbeatDiscoveryClientConditionSpec.groovy

This PR fixes the issue in Micronaut 1.1.3 in which Heartbeat is disabled if not explicitly enabled in the config. This contradicts the documentation which states that Heartbeat is enabled by default.
See #1846 for full details

Issue #1846 Heartbeat event is disabled by default

---

http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
router/src/main/java/io/micronaut/web/router/naming/ConfigurableUriNamingStrategy.java
router/src/test/groovy/io/micronaut/web/router/ConfigurableUriNamingStrategySpec.groovy

In my humble opinion it will be useful to be able to set server context path using property `micronaut.server.context-path` for all controllers.
Also the same ability is already present in Spring Boot [server.servlet.context-path](https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html)
Motivated by [stackoverflow question](https://stackoverflow.com/q/56769848/8112217)

Add micronaut.server.context-path

---

src/main/docs/guide/quickStart/creatingServer.adoc

I think the maven "run" command should be noted in the quick start introduction.

Maven "run" command in the doc introduction

---

inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java

Fix is similar to https://github.com/micronaut-projects/micronaut-core/pull/1339
Fixes https://github.com/micronaut-projects/micronaut-core/issues/1711 issue with using MapStruct and @ConfigurationProperties

Fix multiple attempt to write metadata (Error:  Error occurred writing configuration metadata: Output stream or writer has already been opened.)

---

src/main/docs/guide/ioc.adoc

Developers, not using micronaut-cli, are often not aware of the need to add `testAnnotationProcessor` in the dependencies.

Adding testAnnotationProcessor in dependencies

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java

This is useful when multiple requests are fired in parallel

Trace the HTTP request line in all response types

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java

Fix http port number for declarative HTTP client with manual service discovery configuration and enabled pooling.

#1937 - invalid http port number when pooling is enabled

---

cli/src/main/groovy/io/micronaut/cli/MicronautCli.groovy

There is a "\n\t" in usage outout:
```
λ  mn profile-list
Usage:
create-app [NAME]
create-cli-app [NAME] \n\t create-federation [NAME] --services SERVICE_NAME[,SERVICE_NAME]...
create-function [NAME]
```

Remove extra escape character in cli base usage

---

inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/annotation/DefaultImplementation.java
test-suite/src/test/java/io/micronaut/test/replaces/InterfaceA.java
test-suite/src/test/java/io/micronaut/test/replaces/InterfaceAImpl.java
test-suite/src/test/java/io/micronaut/test/replaces/InterfaceB.java
test-suite/src/test/java/io/micronaut/test/replaces/InterfaceBImpl.java
test-suite/src/test/java/io/micronaut/test/replaces/InterfaceC.java
test-suite/src/test/java/io/micronaut/test/replaces/InterfaceCFactory.java
test-suite/src/test/java/io/micronaut/test/replaces/MockBeanTest.java

This change alters the behaviour of `@Replaces` to use `isAssignableFrom`
This may constitute a breaking change in certain scenarios but fixes what is considered in a bug in the functioning of `@MockBean` and is less surprising than the current behaviour.
This is currently a PR as it may only be included in 1.3 rather than 1.2

Tests and fixes for various @MockBean scenarios

---

http/src/main/java/io/micronaut/http/context/ServerRequestContext.java
http/src/test/groovy/io/micronaut/http/context/ServerRequestContextSpec.groovy

Currently, all of the wrappers in `ServerRequestContext` will completely clear the request context after execution. This has the unexpected behavior of permanently losing the context after instrumenting any code with a request other than the original.
Restoring the prior context allows instrumenting code that should run under a different context or no context at all, without affecting the surrounding code.
Sorry if the spec is not idiomatic or confusing - I'm not very familiar with Spock nor even Groovy.

Restore prior server request context after wrapping execution

---

http/src/main/java/io/micronaut/http/HttpHeaderValues.java

The Javadoc includes the space but the value doesn't.

WIP Add space in Basic and Bearer constants

---

src/main/docs/guide/config/valueAnnotation.adoc

At least that is, what I figured out (maybe I'm mistaken):
- the configuration key/value in the YML/whatever file must exist (exception thrown otherwise)
- no default value can be specified (in contrast to @Value)
If it is correct, what I tried for myself, it would be nice to state this in the documentation.

the configuration entry for @Property must exist; and it does not handle default values.

---

src/main/docs/guide/config/configurationProperties.adoc

The date format example provided was in two digit year, _minutes_, days. More likely if someone is using a LocalDate, they are likely to be expecting something similar to DateTimeFormatter#ISO_LOCAL_DATE, which is yyyy-MM-dd.

More reasonable date format example

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/NettyHttpServerSpec.groovy
http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java
src/main/docs/guide/httpServer/serverConfiguration/dualProtocol.adoc
src/main/docs/guide/toc.yml

Enables what was discussed here #1137. Adds on opt in flag `micronaut.server.dualProtocol` that will bind both http and https to different ports if enabled.

Enables support for http & https at the same time

---

http-server-netty/src/test/groovy/io/micronaut/runtime/http/scope/RequestScopeSpec.groovy
runtime/src/main/java/io/micronaut/runtime/http/scope/RequestAware.java
runtime/src/main/java/io/micronaut/runtime/http/scope/RequestCustomScope.java

The goal here is to reduce another lookup to the context holder since we already have access to the request and the bean it should not be necessary

Allow `@RequestScope` beans to get access to the request

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/NettyHttpServerSpec.groovy

After getting this into real use in the micronaut-acme project found
that it was firing the startup event twice now. This is not ideal as it
triggered the certificate validation process twice.
Also it looks like if using a random port failed to bind and it retried
it would have also suffered from this
(Not sure much would have been affected by this other than tests cases)

Dual port patch

---

http-server-netty/build.gradle
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/NettyHttpPortContentionSpec.groovy

cc @graemerocher here is the real fix for the flaky server port issues. `ValidateAnnotationMetadataSpec` is still an issue that fails occasionally but hopefully this build is green.

Fix for if port contention happened we would not set the right internal port

---

src/main/docs/guide/aop/introductionAdvice.adoc

`snippet::io.micronaut.docs.aop.introduction.StubIntroduction` is repeated
Correct snippet for StubExample is:
`snippet::io.micronaut.docs.aop.introduction.StubExample`

#1265 correct snippet for StubExample

---

runtime/src/main/java/io/micronaut/runtime/Micronaut.java

When using a GraalVM native image, at present you have to make your application class look like:
```
package com.example;
import io.micronaut.runtime.Micronaut;
import sun.misc.Signal;
import sun.misc.SignalHandler;
public class Application {
public static void main(String[] args) {
SignalHandler sh = sig -> System.exit(128 + sig.getNumber());
Signal.handle(new Signal("INT"), sh);
Signal.handle(new Signal("TERM"), sh);
Micronaut.run(Application.class);
}
}
```
in order to get the shutdown hooks to run, as at present there's no default signal handler in native images (https://github.com/oracle/graal/issues/465).
However when you do this, I think because native images are faster, you sometimes get this exception:
```
java.lang.InterruptedException: null
at …
```

Stop log noise by handling interrupt on shutdown latch

---

inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
settings.gradle
test-suite-helper/src/main/java/io/micronaut/testsuitehelper/TestGeneratingAnnotationProcessor.java
test-suite-helper/src/main/resources/META-INF/services/javax.annotation.processing.Processor
test-suite/build.gradle
test-suite/src/test/java/io/micronaut/docs/aop/introduction/generics/GenericPublisher.java
test-suite/src/test/java/io/micronaut/docs/aop/introduction/generics/GenericsIntroductionSpec.java
test-suite/src/test/java/io/micronaut/docs/aop/introduction/generics/PublisherIntroduction.java
test-suite/src/test/java/io/micronaut/docs/aop/introduction/generics/PublisherProxy.java
test-suite/src/test/java/io/micronaut/docs/aop/introduction/generics/SpecificEvent.java
test-suite/src/test/java/io/micronaut/docs/aop/introduction/generics/SpecificPublisher.java
test-suite/src/test/java/io/micronaut/docs/inject/generated/MainBean.java
test-suite/src/test/java/io/micronaut/docs/inject/generated/SomeBean.java
test-suite/src/test/java/io/micronaut/docs/inject/generated/VerifyDefinitionInjectionSpec.java

fixed regression introduced in 8f539ac for BeanDefinitionInjectProcessor generating definitions of beans using interfaces generated in annotation processor.
Also added test cases for #1649 and #1667

fixed regression for BeanDefinitionInjectProcessor

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/main/java/io/micronaut/http/client/exceptions/HttpClientErrorDecoder.java
http-client/src/main/java/io/micronaut/http/client/exceptions/HttpClientResponseException.java
http-client/src/test/groovy/io/micronaut/http/client/CustomErrorTypeSpec.groovy

Submitting a PR because this introduces a breaking change in `HttpClientErrorDecoder`. The class isn't used in a context that allows for extension however it is not marked `@Internal`. I think the likelihood of anyone using this class directly is very low.

Use an Argument instead of Class for the error type. Fixes #2203

---

src/main/docs/guide/httpClient/lowLevelHttpClient/clientBasics.adoc

I recreated the PR on 1.2.x, and I'll close the old PR.

Fix typo in Kotlin example with httpclient

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java

Unsupported http status emits exception, but does not remove the pipeline handler... leaving `ReadTimeoutHandler` still attached and active!

Issue 2228: fix missing cleanup code

---

inject-groovy/src/test/groovy/io/micronaut/inject/factory/ParametrizedFactorySpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/factory/parameterizedfactory/D.java
inject-java/src/test/groovy/io/micronaut/inject/factory/parameterizedfactory/ParametrizedFactorySpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

When all parameters are marked as Nullable and none arguments provided, bean initialization fails
```
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.inject.ParametrizedBeanInjectionSpec$ParametrizedBean]
Message: Missing bean arguments for type: io.micronaut.inject.ParametrizedBeanInjectionSpec$ParametrizedBean. Requires arguments: SomeBean someBean
```

Injection into parametrized bean fails if no arguments are provided

---

core/src/main/java/io/micronaut/core/value/PropertyResolver.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesWithRawMapSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/MyHibernateConfig.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/MyHibernateConfig2.java
inject-java/src/test/groovy/io/micronaut/inject/value/singletonwithvalue/A.java
inject-java/src/test/groovy/io/micronaut/inject/value/singletonwithvalue/ValueSpec.groovy
inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy

This change alters Micronaut to store the raw keys and fall back to raw resolution if a value is not found. It also makes Micronaut truly respect `StringConversion.RAW` when injecting maps which it previously did not and results in issues like #2218
Also includes some performance optimizations and in general has no impact on startup time, however there is probably a marginal increases in memory usage to keep the raw keys around, although given these are referencing existing values already help by System.env() and System.properties() maybe it is not a big deal.

Allow resolution of values using actual raw keys. Fixes #2218

---

http-client/src/main/java/io/micronaut/http/client/NettyClientHttpRequest.java
http-client/src/test/groovy/io/micronaut/http/client/MultiHeaderSpec.groovy
http-netty/src/main/java/io/micronaut/http/netty/NettyHttpHeaders.java

From https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html: `Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list ...`
The PR contains changes that copies request headers in way that preserves multiple header entries with the same name, and also an improvement to the `@Header` annotation so it supports injecting a list of values from a header that is defined multiple times.

Support multiple headers with same field name

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/consumes/RouteComplexitySpec.groovy
http/src/main/java/io/micronaut/http/uri/UriTemplate.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java

Creating a PR because this contains a slight change in behavior
A request to `/other/a/b/c/d` would previously match `/other/{a}{/b+}` over `/other/{a}{/b}{/c}/d` because the former has less variables. The change makes more raw segments have priority over the variable segments. Previously routes were ordered by variable segment count then raw count. This change makes it raw segment count then variable segment count.

Route priority

---

src/main/docs/guide/quickStart/buildCLI/installMacPorts.adoc
src/main/docs/guide/toc.yml

I maintain the Micronaut CLI port for [MacPorts](https://www.macports.org). This PR adds instructions for installing the Micronaut CLI using MacPorts.

Add instructions on how to install CLI via MacPorts

---

src/main/docs/guide/introduction/whatsNew.adoc

The heading for "RSS 2.0 Module Included in BOM" was h2 instead of h3, so it didn't match the other items for the What's new in version 1.2.x section.

Fix inconsistent heading level

---

discovery-client/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
discovery-client/src/test/groovy/io/micronaut/discovery/propertystore/AWSPropertyStoreMockConfigurationClientSpec.groovy

Attempt at fixing https://github.com/micronaut-projects/micronaut-core/issues/2296
It will keep calling AWS as long as the parameter store returns a "nextToken". Should this be limited in any way? A configurable limit of how many pages it will attempt at paginating?
Also added some TRACE logging to AWSParameterStoreConfigClient to ease what parameters are retrieved from paramstore.

adds support for pagination in GetParametersByPath for AWSParameterStore

---

test-suite/src/test/java/io/micronaut/docs/events/factory/EngineInitializer.java

while reading the docs, I noticed a code snippet where the return statement could be simplified

simplify return statement on doc snippet

---

tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MdcInstrumenterSpec.groovy

Currently, MDC instrumenter always clear the MDC context at the end of
the instrumented execution cycle.  When an Async operation is run as blocking,
the entire execution happens in same thread as the calling thread. At the end of the
execution of the asynchronous operation, the current thread MDC will be cleared, which
can lead to unexpected loss of context.
This change proposes that during an instrumented execution, the MDC
context is only overloaded and at the end of the execution the previous
state is restored.

Preserve MDC original context after instrumented operation completion

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectorSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/TestNamed.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject/src/main/java/io/micronaut/inject/beans/visitor/BeanPropertyWriter.java
inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java

This adds support for introspections for interfaces. Also removes the restriction that an introspection must have a constructor.

Support introspections for interfaces. Issue #1968

---

core/src/main/java/io/micronaut/core/bind/annotation/Bindable.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/config/GroovyConfigurationMetadataBuilder.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/JavaConfigurationMetadataBuilder.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertyInterfaceSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/foreach/InterfaceConfig.java
inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java
runtime/src/main/java/io/micronaut/runtime/context/env/ConfigurationAdvice.java
runtime/src/main/java/io/micronaut/runtime/context/env/ConfigurationIntroductionAdvice.java
src/main/docs/guide/config/immutableConfig.adoc
test-suite-groovy/src/test/groovy/io/micronaut/docs/config/itfce/Engine.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/config/itfce/EngineConfig.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/config/itfce/Vehicle.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/config/itfce/VehicleSpec.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/immutable/VehicleSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/itfce/Engine.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/itfce/EngineConfig.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/itfce/Vehicle.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/config/itfce/VehicleSpec.kt
test-suite/src/test/java/io/micronaut/docs/config/itfce/Engine.java
test-suite/src/test/java/io/micronaut/docs/config/itfce/EngineConfig.java
test-suite/src/test/java/io/micronaut/docs/config/itfce/Vehicle.java
test-suite/src/test/java/io/micronaut/docs/config/itfce/VehicleSpec.java
validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java

Whilst working on the support for immutable configuration properties it seemed to me it would be much nicer to simply allow `@ConfigurationProperties` to be defined for interfaces. It is less verbose for Java, Groovy and Kotlin. This PR adds support for that. I need to think if we can support `@EachProperty` but this is start.

Support for @ConfigurationProperties on interfaces

---

core/src/main/java/io/micronaut/core/convert/ConversionContext.java
core/src/main/java/io/micronaut/core/convert/DefaultArgumentConversionContext.java
core/src/main/java/io/micronaut/core/convert/value/ConvertibleMultiValues.java
core/src/main/java/io/micronaut/core/convert/value/ConvertibleValues.java
core/src/main/java/io/micronaut/core/type/Argument.java
core/src/main/java/io/micronaut/core/type/DefaultArgument.java
http-client/src/main/java/io/micronaut/http/client/exceptions/HttpClientErrorDecoder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/CompletableFutureBodyBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/PublisherBodyBinder.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/cors/CorsFilterSpec.groovy
http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
http-server/src/main/java/io/micronaut/http/server/cors/CorsOriginConverter.java
http/src/main/java/io/micronaut/http/HttpHeaders.java
http/src/main/java/io/micronaut/http/MediaType.java
runtime/src/main/java/io/micronaut/cache/interceptor/CacheInterceptor.java
runtime/src/main/java/io/micronaut/scheduling/io/watch/FileWatchCondition.java
session/src/main/java/io/micronaut/session/binder/SessionArgumentBinder.java

Changes
-------
* Added ArgumentConversionContext constants in ConversionContext
* Replaced Argument.of and use of argument classes with
ConversionContext constants where possible
* Added getFirst method in ConvertibleMultiValues that accepts
ArgumentConversionContent parameter
Partially addresses issue #2355

Use Argument constants where possible instead of class

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/web/router/version/VersionControllerSpec.groovy
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
router/src/main/java/io/micronaut/web/router/Router.java
router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java

Fixes #2305 and added new methods `findAny(uri, context)` and `find(httpMethod, requestPath, request)` methods to `Router.java` and implemented VersionFilter check in `FilteredRouter.java`.

Apply VersionFilter to find the route by HTTP Method and URI logic

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorEnd.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorStart.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/config/GroovyConfigurationMetadataBuilder.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/AstAnnotationUtils.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/PublicAbstractMethodVisitor.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/AbstractGroovyElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyClassElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyConstructorElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyEnumElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyFieldElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyMethodElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyParameterElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyPropertyElement.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyVisitorContext.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/LoadedVisitor.groovy
inject-groovy/src/test/groovy/io/micronaut/AbstractBeanDefinitionSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilderSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configuration/GroovyConfigurationMetadataBuilderSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/introspections/Person.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/introspections/PersonConfiguration.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
router/src/test/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilderSpec.groovy

Fixes visitorContext.getClass methods not being able to find classes currently being compiled

Use the compilation unit for retrieving classes

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/PublisherBodyBinder.java
router/src/main/java/io/micronaut/web/router/AbstractRouteMatch.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedBodyRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedCookieValueRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedHeaderRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedPartRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedPathVariableRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedQueryValueRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedRequestAttributeRouteException.java
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedRouteException.java

Each Bindable annotation defined under io.micronaut.http.annotation now
has a dedicated UnsatisfiedRouteException.
Resolves issue #2249
For 1.3.x

Specialized UnsatisfiedRouteException

---

src/main/docs/guide/management/buildingEndpoints/endpointMethod.adoc
test-suite/src/test/java/io/micronaut/docs/server/endpoint/CurrentDateEndpoint.java

This pull request fixes the broken code samples in section [14.1.2 Endpoint Methods](https://docs.micronaut.io/snapshot/guide/index.html#endpointMethod) of the Management documentation.

Fix code samples in section 14.1.2 of Management documentation

---

http-client/src/main/java/io/micronaut/http/client/BlockingHttpClient.java
http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/main/java/io/micronaut/http/client/FullNettyClientHttpResponse.java
http-client/src/main/java/io/micronaut/http/client/HttpClientConfiguration.java
http-client/src/test/groovy/io/micronaut/http/client/ExceptionOnErrorStatusSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/config/DefaultHttpClientConfigurationSpec.groovy

DefaultHttpClient no longer throws HttpClientResponseException when an
error is returned and the response's errorType matches bodyType.
Resolves issue #2193
Targeting 1.3.x release

http-client: exceptionless handling of error responses

---

tracing/src/main/resources/META-INF/native-image/io.micronaut/micronaut-tracing/native-image.properties

it adds following classes:
* `io.micronaut.tracing.brave.BraveTracerFactory`
* `io.micronaut.tracing.brave.instrument.http.HttpTracingFactory`
* `io.micronaut.tracing.brave.log.Slf4jCurrentTraceContextFactory`
* `io.micronaut.tracing.brave.sender.HttpClientSenderFactory`
* `io.micronaut.tracing.instrument.rxjava.RxJava1TracingInstrumentation`
..for the `initialize-at-run-time`

Native-image.properties that defers the initialization of various classes to run-time

---

src/main/docs/guide/appendix/problems.adoc

The issue also appears on Linux. I had this problem a few days ago. On my armv7 hardware, the test application (mentioned in the Getting Started guide) took 64 seconds to start. After the fix, it took 16 seconds.

Long start time on Linux as well

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
management/src/main/java/io/micronaut/management/endpoint/EndpointDefaultConfiguration.java
management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
management/src/main/java/io/micronaut/management/endpoint/processors/DeleteEndpointRouteBuilder.java
management/src/main/java/io/micronaut/management/endpoint/processors/ReadEndpointRouteBuilder.java
management/src/main/java/io/micronaut/management/endpoint/processors/WriteEndpointRouteBuilder.java
management/src/test/groovy/io/micronaut/management/endpoint/EndpointsPortSpec.groovy
router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
router/src/main/java/io/micronaut/web/router/RouteBuilder.java
router/src/main/java/io/micronaut/web/router/Router.java
router/src/main/java/io/micronaut/web/router/UriRoute.java
router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java
src/main/docs/guide/management/providedEndpoints.adoc

This resolves #948 by adding a condition to each `@Endpoint` route and exposing an additional port.

Support for customizing the management port. Fixes #948

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
websocket/src/main/java/io/micronaut/websocket/annotation/ServerWebSocket.java

This is the server variant of https://github.com/micronaut-projects/micronaut-core/pull/2513
By this commit I would like to give possibility to set subprotocols in ServerWebSocket annotation and I have also added code to pass it properly to netty.
Default value: empty string, which will be turned to null in the UpgradeHandler to keep the same correct behaviour when no subprotocol is set.
Example of use:
```java
@ServerWebSocket(value = "${" + GraphQLConfiguration.PREFIX + "." + GraphQLConfiguration.GraphQLWsConfiguration.PATH + ":"
+ GraphQLConfiguration.GraphQLWsConfiguration.DEFAULT_PATH + "}", subprotocols = "graphql-ws")
```
I encountered the need for the fix working on support for subscriptions in micronaut-graphql, and running into problems with chrome specifically because the …

Add possibility to set subprotocols on the server web socket

---

core/src/main/java/io/micronaut/core/cli/CommandLineParser.java

Fix for #2581: allow empty values for command line parameter

---

test-suite/src/test/java/io/micronaut/docs/qualifiers/annotation/VehicleSpec.java

I don't see why we use the Vehicule from another package here, so I guess it may be a mistake that this PR aims to fix.

Fix wrong import in test

---

inject-java/src/main/java/io/micronaut/annotation/processing/AbstractInjectAnnotationProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/PackageConfigurationInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java

This change adds a ability to enable incremental annotation processing by limiting the annotations that Micronaut can process. Fixes #2718
Example config:
```
tasks.withType(JavaCompile) {
options.compilerArgs = [
'-Amicronaut.processing.incremental=true',
'-Amicronaut.processing.annotaions=com.foo.*',
]
}
```

Add option to enable incremental annotation processing

---

core/src/main/java/io/micronaut/core/annotation/AnnotationValue.java
core/src/main/java/io/micronaut/core/annotation/AnnotationValueBuilder.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/annotation/SourceRetentionSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/annotation/AnnotationTransformerSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/annotation/ToTransform.java
inject-java-test/src/test/groovy/io/micronaut/inject/annotation/ToTransformRetention.java
inject-java-test/src/test/groovy/io/micronaut/inject/annotation/ToTransformRetentionTransformer.java
inject-java-test/src/test/groovy/io/micronaut/inject/annotation/ToTransformTransformer.java
inject-java-test/src/test/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationTransformer
inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
inject-java/src/test/groovy/io/micronaut/inject/annotation/SourceRetentionSpec.groovy
inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
inject/src/main/java/io/micronaut/inject/annotation/AnnotationTransformer.java
inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
inject/src/main/java/io/micronaut/inject/annotation/EnvironmentAnnotationValue.java
inject/src/main/java/io/micronaut/inject/annotation/NamedAnnotationTransformer.java
inject/src/main/java/io/micronaut/inject/annotation/TypedAnnotationTransformer.java

This change introduces a new interface, `AnnotationTransformer`, that discards the original annotation thus adding the ability for extensions to optimize memory consumption by not retaining metadata that is not used at runtime.
In addition this change provides a solution to transform existing runtime annotations to source level annotations which provides a potential solution for #2703.
This change is also breaking as it alters Micronaut to properly respect source level retention defined in annotations. Source level annotations will no longer be retained metadata from Micronaut 2.0 onwards.

Support for transforming annotations values and source retention 

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/consumes/ConsumesMatchesRouteSpec.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/visitor/GroovyVisitorContext.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaVisitorContext.java
inject/src/main/java/io/micronaut/inject/util/VisitorContextUtils.java
inject/src/main/java/io/micronaut/inject/visitor/TypeElementVisitor.java
inject/src/main/java/io/micronaut/inject/visitor/VisitorContext.java
inject/src/test/groovy/io/micronaut/inject/util/VisitorContextUtilsSpec.groovy
validation/src/main/java/io/micronaut/validation/properties/MixedCasePropertyTypeElementVisitor.java
validation/src/main/java/io/micronaut/validation/routes/RouteValidationVisitor.java
validation/src/main/java/io/micronaut/validation/websocket/WebSocketVisitor.java

- Needed to fix issue micronaut-projects/micronaut-openapi#108
By enabling annotation processors arguments, one can remove the need
for ugly System properties on thirdy party visitors. E.g.:
micronaut-openapi
- Fixing http-server-netty integration test, according to HTTP spec regarding to
Content-Type negotiation:
See https://tools.ietf.org/html/rfc7231#section-3.1.1.5

Enabling Visitors to declare annotation processors options.

---

inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java

to keep compatibility for micronaut-openapi which depends
on an older version of micronaut-core.

Set annotation processor options as system properties

---

.dependabot/config.yml

Allows auto-merging AWS SDK patch releases.

Dependabot config file

---

http-netty/src/main/java/io/micronaut/http/netty/websocket/NettyRxWebSocketSession.java
websocket/src/main/java/io/micronaut/websocket/WebSocketSession.java

Helps in cases when the user wants to send the same message to multiple sessions, like this:
```
public void sendToMultipleChannels(final String json, final Collection<WebSocketSession> sessions) {
final TextWebSocketFrame frame = new TextWebSocketFrame(json);
try {
Iterator<WebSocketSession> iterator = sessions.iterator();
while(iterator.hasNext()) {
WebSocketSession s = iterator.next();
if (s.isOpen()) {
s.sendAsync(frame.retainedDuplicate(), MediaType.APPLICATION_JSON_TYPE);
} else {
iterator.remove();
}
}
} finally {
frame.release();
}
}
```
The second commit merely exposes the writable status. This is an important piece of information in case we have a slow consumer whose send-buffer is already full. Instead of letting netty increase the buffer size (and eventually reaching OOM) we …

Avoid re-encoding messages if already provided as a Frame

---

src/main/docs/guide/config/propertySource.adoc

It is common for java developers to use camel-case in their variable names. Include a caution against using that convention in a configuration, since Micronaut does not translate environment variables for camel-case configuration values.

Include caution for property sources

---

core/src/main/java/io/micronaut/core/io/socket/SocketUtils.java

Because `SocketUtils.isTcpPortAvailable()` is only attempting to connect to `localhost`, there is no need for a long timeout (0 means unlimited).
Using an unlimited timeout may lead to an increase in test time when `@MicronautTest` is used massively because `NettyHttpServer.stop()` is using this function.

Use low timeout when attempting to connect to localhost

---

cli/src/main/groovy/io/micronaut/cli/io/support/GradleBuildTokens.groovy

Creating a project with the following command does not result in a buildable project because the graal-native-image feature is adding multiple annotation processors to the build.gradle file and gradle cannot find the versions for these dependencies. This prevents `./gradlew assemble` from generating a jar file that can then be used for making an image with `docker-build.sh`.
```
mn create-cli-app --lang=groovy --features=graal-native-image groovycli
```
This patch is simply adding the micronaut-bom to annotation processors in the groovy project.
See https://github.com/micronaut-projects/micronaut-picocli/issues/23 for more information.

Add micronaut-bom for annotationProcessor in groovy projects

---

http-netty/src/main/java/io/micronaut/http/netty/websocket/AbstractNettyWebSocketHandler.java

This PR changes the `AbstractNettyWebSocketHandler` such that it closes the WebSocket session using the close code that is specified by the client. 
Reproducing the steps in #2851 now results in the following:

Respect client close code in WebSocketHandler. Fixes #2851

---

management/build.gradle
management/src/main/java/io/micronaut/management/health/indicator/jdbc/JdbcIndicator.java

This is related to https://github.com/micronaut-projects/micronaut-data/pull/436 - transactional data source proxy should not be used by this health indicator.
This patch also contains a dependency substitution for jdbc module, otherwise tests are broken because it uses version 1.1.4 which lacks 6b146e4c4067257669438b0e8d20c775b2cb7915. Perhaps it might be a good idea to do something like this for all micronaut-core modules in all tests.

Use DataSourceResolver in JDBC health indicator

---

core/src/main/java/io/micronaut/core/async/publisher/Publishers.java
core/src/main/java/io/micronaut/core/type/ReturnType.java
http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/ResponseAndStreamSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/ServerRedirectSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/docs/httpstatus/HttpStatusSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/rxjava2/RxHttpPostSpec.groovy
http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/ContentNegotiationSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/status/StatusControllerSpec.groovy
http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java
http/src/main/java/io/micronaut/http/HttpRequestFactory.java
http/src/main/java/io/micronaut/http/annotation/Consumes.java
http/src/main/java/io/micronaut/http/annotation/Produces.java
inject/src/main/java/io/micronaut/context/AbstractExecutableMethod.java
management/src/main/java/io/micronaut/management/endpoint/health/filter/HealthResultFilter.java
router/src/main/java/io/micronaut/web/router/AbstractRouteMatch.java
router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
router/src/main/java/io/micronaut/web/router/Route.java
router/src/main/java/io/micronaut/web/router/RouteInfo.java
router/src/main/java/io/micronaut/web/router/RouteMatch.java
runtime/src/main/java/io/micronaut/reactive/reactor/converters/ReactorConverterRegistrar.java
runtime/src/main/java/io/micronaut/reactive/rxjava2/converters/RxJavaConverterRegistrar.java
validation/src/test/groovy/io/micronaut/validation/ValidatedSpec.groovy

This PR is a rewrite of RoutingInBoundHandler to improve performance, reduce the reactive call stack (issue #2566) and allow response chunking (issue #2902) via filter.

Rewrite the RoutingInBoundHandler to simplify trace and allow chunking

---

runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonMetadataConfiguration.java

This commit fixes #2934 AmazonComputeInstanceMetadataResolver has an invalid path.

Fix incorrect URL formation

---

http/src/main/java/io/micronaut/http/HttpHeaders.java

Adds the [`Link`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link) header to the `HttpHeaders` class in Micronaut's HTTP core. The _`Link`_ header is used as an alternate expression of the `<link ... />` tag in HTML pages, for instance with [DNS prefetching](https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch) or [asset pre-loading](https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content).

Add `Link` header to `HttpHeaders`

---

http/src/main/java/io/micronaut/http/HttpHeaders.java

This small change adds the [`Cross-Origin-Resource-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)) header to the `HttpHeaders` class in Micronaut's HTTP core. *Cross-Origin Resource Policy* allows web apps and sites to opt-in to additional protections against cross-origin vulnerabilities (speculative side-channel attacks, as well as Cross-Site Script Inclusion attacks, according to MDN).

Add `Cross-Origin-Resource-Policy` header to `HttpHeaders`

---

http/src/main/java/io/micronaut/http/HttpHeaders.java

Adds the [`Referrer-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy) header to the `HttpHeaders` class in Micronaut's HTTP core. This header is used to limit/secure the use of the `Referer` header with potentially unsafe/malicious cross origin actors.

Add `Referrer-Policy` header to `HttpHeaders`

---

http/src/main/java/io/micronaut/http/HttpHeaders.java

This small change adds the [`Feature-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Feature_Policy) header to the `HttpHeaders` class in Micronaut's HTTP core. *Feature Policy* allows the server to restrict various browser features when serving an HTML document.

Add `Feature-Policy` header to `HttpHeaders`

---

http/src/main/java/io/micronaut/http/HttpHeaders.java

This small change adds the [`SourceMap`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/SourceMap) header to the `HttpHeaders` in Micronaut's HTTP core. This header allows a server which is serving a JavaScript or stylesheet resource to indicate a URL for a source-map relating to the resource.

Add `SourceMap` header to `HttpHeaders`

---

http/src/main/java/io/micronaut/http/HttpHeaders.java

Small change to add support for [_Client Hints_](https://developer.mozilla.org/en-US/docs/Glossary/Client_hints) headers to the `HttpHeaders` enumeration in Micronaut's core HTTP layer. This includes response headers sent to indicate hint support ([`Accept-CH`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-CH)) and request headers sent to indicate hint values (like [`DPR`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/DPR), for instance).
This lays the groundwork for PRs downstream to add support for [Client Hints](https://developer.mozilla.org/en-US/docs/Glossary/Client_hints) writ-large, but for now, it's just the headers themselves.
Sources for docs/specs regarding _Client Hints_:
- [MDN: _Client …

Add Client Hints headers to `HttpHeaders`

---

function/src/main/java/io/micronaut/function/executor/AbstractExecutor.java

This will be handy since AbstractExecutor is a parent class for classes such as `MicronautRequestHandler`.

AbstractExecutor implements ApplicationContextProvider

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/WriteBufferWaterMarkConverter.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/NettyHttpServerConfigurationSpec.groovy
http-server-netty/src/test/java/io/micronaut/http/server/netty/converters/WriteBufferWaterMarkConverterTest.java

https://netty.io/4.1/api/io/netty/channel/ChannelOption.html#WRITE_BUFFER_WATER_MARK introduced a new way of configuring watermarks that requires a new TypeConverter in netty to be able to configure it through `NettyHttpServerConfiguration`.
The `WriteBufferWaterMarkConverterTest` is rather heavy (and java) but could not find a better way of ensuring that the TypeConverter actually kicks in and hands over the config values to `ServerBootstrap`. Feel free to amend.
Solves https://github.com/micronaut-projects/micronaut-core/issues/2970

Support the WRITE_BUFFER_WATER_MARK ChannelOption of netty.

---

src/main/docs/guide/ioc/contextEvents.adoc
test-suite-groovy/src/test/groovy/io/micronaut/docs/context/events/listener/SampleEventListener.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/context/events/listener/SampleEventListener.kt
test-suite/src/test/java/io/micronaut/docs/context/events/listener/SampleEventListener.java

Adds some docs about StartupEvent and ShutdownEvent to the context events section of the docs.

Fixes #2831 document startup and shutdown events

---

http-client/src/test/groovy/io/micronaut/http/client/services/ManualHttpServiceDefinitionSpec.groovy

The 'test working SSL configuration' was flaky due to the fact
that it was depending on the exact availability of the port 8443
in the host machine in order to pass.
The test is now using a random server port, which will allow us
to remove the `@Retry` that we had there before, avoiding failing
this test due to specific port unavailability.

Fix flaky test in ManualHttpServiceDefinitionSpec

---

http-netty/src/main/java/io/micronaut/http/netty/channel/DefaultEventLoopGroupFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/EpollAvailabilityCondition.java
http-netty/src/main/java/io/micronaut/http/netty/channel/EpollEventLoopGroupFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/EventLoopGroupFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/KQueueAvailabilityCondition.java
http-netty/src/main/java/io/micronaut/http/netty/channel/KQueueEventLoopGroupFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/NioEventLoopGroupFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/converters/ChannelOptionFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/converters/DefaultChannelOptionFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/converters/EpollChannelOptionFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/converters/KQueueChannelOptionFactory.java
http-server-netty/build.gradle
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/converters/NettyConverters.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/configuration/NettyHttpServerConfigurationSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/converters/WriteBufferWaterMarkConverterSpec.groovy

Options can be specified as regular options and childOptions.
Issue:  https://github.com/micronaut-projects/micronaut-core/issues/2066
alternative PR: https://github.com/micronaut-projects/micronaut-core/pull/2106

Fix #2066 - Add support for native transport channel options

---

discovery-client/src/main/java/io/micronaut/discovery/consul/ConsulConfiguration.java
discovery-client/src/main/java/io/micronaut/discovery/consul/ConsulServiceInstance.java
discovery-client/src/main/java/io/micronaut/discovery/consul/client/v1/AbstractServiceEntry.java
discovery-client/src/main/java/io/micronaut/discovery/consul/client/v1/ServiceEntry.java
discovery-client/src/main/java/io/micronaut/discovery/consul/registration/ConsulAutoRegistration.java
discovery-client/src/test/groovy/io/micronaut/discovery/consul/ConsulAutoRegistrationSpec.groovy
discovery-client/src/test/groovy/io/micronaut/discovery/consul/ConsulMockAutoRegistrationSpec.groovy
src/main/docs/guide/cloud/serviceDiscovery/serviceDiscoveryConsul.adoc

As #2615 describes, until now it was not possible to specify the attribute [meta](https://www.consul.io/api/agent/service.html#meta) in the  Consul registration customization.
This PR adds a new configuration property `consul.client.registration.meta` which allows the user to define custom metadata when registering a service in Consul.
I checked the test which covers the tag property and I have tried to add corresponding tests for the metadata.
Different from the tag property, Consul [does not support](https://www.consul.io/api/health.html#parameters-2) simple querying based on the meta attribute. Therefore, I have not changed the `ConsulDiscoveryConfiguration`.
I have updated the configuration example in the documentation so that it includes now the new property. Running this example …

Allow configuration of metadata when registering an application in Consul

---

discovery-client/build.gradle
discovery-client/src/main/java/io/micronaut/discovery/oraclecloud/vault/config/OracleCloudVaultClientConfiguration.java
discovery-client/src/main/java/io/micronaut/discovery/oraclecloud/vault/config/OracleCloudVaultConfigurationClient.java
discovery-client/src/main/java/io/micronaut/discovery/oraclecloud/vault/config/package-info.java
discovery-client/src/test/groovy/io/micronaut/discovery/oraclecloud/VaultConfigurationTest.groovy
inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
src/main/docs/guide/cloud/cloudConfiguration/distributedConfigurationOracleCloudVault.adoc
src/main/docs/guide/toc.yml

This feature adds support for Oracle Cloud Vault. Users can define a list of vaults in `bootstrap.yml` and each vault will be listed and the secrets within them retrieved and set in to configuration variables in the application. The feature

Add Support For Oracle Cloud Vault

---

core/build.gradle
core/src/main/java/io/micronaut/core/graal/CacheSubstitutions.java
core/src/main/resources/META-INF/native-image/io.micronaut.core/cache-caffeiene-graal/native-image.properties
core/src/main/resources/META-INF/native-image/io.micronaut.core/cache-caffeiene-graal/reflection-config.json

I talked with James about this change I did https://github.com/micronaut-projects/micronaut-cache/pull/108/commits/3067eb3077926eca21600353ef059c01cb6eba4f in micronaut-cache and we agreed on moving that to micronaut-core.
The rationale behind this change is that we're using the shaded version of Caffeine in Micronaut Core so we should add support for GraalVM for those shaded classes, meaning:
- The GraalVM substitution for `io.micronaut.caffeine.cache.UnsafeRefArrayAccess`, that only adds the graalvm native image dependency as compileOnly.
- We can't use `@TypeHint` to generate the GraalVM configuration because this goes in `micronaut-core` and can't depend on any other module. That's why I added the config files directly for the two shaded classes that we need: …

Graalvm support for the shaded version of caffeine

---

http-server/src/main/java/io/micronaut/http/server/exceptions/URISyntaxHandler.java
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/urisyntax/MalformedUriSpec.groovy

Fixes #2606 
This PR adds a default ExceptionHandler for URISyntax exception and a test to verify the behaviour.
Reproducing the steps in #2606 now results in the following:
```
$ curl -v 'http://localhost:8080/<>'
*   Trying ::1:8080...
* Connected to localhost (::1) port 8080 (#0)
> GET /<> HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Type: application/json
< content-length: 70
< connection: close
< 
* Closing connection 0
{"message":"Malformed URI: Illegal character in path at index 1: /<>"}
```

Return BadRequest for malformed URI requests.

---

function/src/main/java/io/micronaut/function/executor/AbstractExecutor.java
function/src/main/java/io/micronaut/function/executor/FunctionInitializer.java
function/src/main/java/io/micronaut/function/executor/StreamFunctionExecutor.java

This will allow classes such as [MicronautRequestHandler](https://github.com/micronaut-projects/micronaut-aws/blob/master/function-aws/src/main/java/io/micronaut/function/aws/MicronautRequestHandler.java) to close its application context easily.

refactor: Abstract Executor implement closeable

---

aop/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
core/src/main/java/io/micronaut/core/annotation/Generated.java
graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/CustomVisitorSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject-java/src/test/groovy/io/micronaut/visitors/CustomVisitorSpec.groovy
inject/src/main/java/io/micronaut/inject/beans/visitor/BeanIntrospectionWriter.java
inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
inject/src/main/java/io/micronaut/inject/writer/ExecutableMethodWriter.java
test-suite-helper/src/main/java/io/micronaut/testsuitehelper/TestGeneratingAnnotationProcessor.java
test-suite/src/test/java/io/micronaut/docs/inject/generated/VerifyIntrospectionSpec.java

#2901 
This fix allows the `TypeElementVisitorProcessor` to be executed for each round. This implies several changes :
- the `LoadedVisitor` are initialized once and for all in the `init` method
- `javaVisitorContext.finish` is only called once every class has been generated and processed (this call is responsible for writing the services)
- some visitors needed to be modified to ensure that the files they generated were written only once
- a `@Generated` annotation was added to every generated classes, preventing them to be handled by the `TypeElementVisitorProcessor`
The PR may need some improvements (and an additional control that I didn't miss any Visitor), however the result seems to be OK on my end.

Issue #2901 - Improve bean introspection

---

test-suite/src/test/groovy/io/micronaut/tracing/jaeger/HttpTracingSpec.groovy
tracing/src/main/java/io/micronaut/tracing/instrument/http/OpenTracingServerFilter.java

Simple PR, just removed 2 lines that set span operation name second time which is not needed and make it impossible for user to change it. Added test to show it.
Fixes #3084 .

Fix overwritting of span operation name in OpenTracingServerFilter

---

runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
runtime/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy

#3114
This fix bypasses the `BeanIntrospectionModule` when a delegatedType is detected (the delegatedType still being processed by the `BeanIntrospectionModule` in a second pass.

Issue #3114 - Allow beans annotated with JsonCreator.Mode.DELEGATING to be deserialized

---

inject/src/main/java/io/micronaut/context/StaticMessageSource.java

During reading codes for working on [this issue](https://github.com/micronaut-projects/micronaut-core/issues/2617), I found two typos in `StaticMessageSource`.
I think the phrase `The the message` is `The message`, so I modified.
And I think [here](https://github.com/micronaut-projects/micronaut-core/blob/88a809f176ddf85c0c8456f45f4fd527cfbf8257/inject/src/main/java/io/micronaut/context/StaticMessageSource.java#L72-L74) is more readable by coding with one line.
`return Optional.of(msg);`

Modify some typos and make a line readable

---

http-client/src/test/groovy/io/micronaut/http/client/aop/RequestBeanSpec.groovy
http/src/main/java/io/micronaut/http/annotation/CookieValue.java
http/src/main/java/io/micronaut/http/annotation/Header.java
http/src/main/java/io/micronaut/http/annotation/PathVariable.java
http/src/main/java/io/micronaut/http/annotation/RequestBean.java
http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java
http/src/main/java/io/micronaut/http/bind/binders/RequestBeanAnnotationBinder.java
validation/src/main/java/io/micronaut/validation/routes/RouteValidationVisitor.java
validation/src/main/java/io/micronaut/validation/routes/rules/MissingParameterRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/NullableParameterRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/RequestBeanParameterRule.java
validation/src/test/groovy/io/micronaut/validation/routes/MissingParameterRuleSpec.groovy
validation/src/test/groovy/io/micronaut/validation/routes/NullableParameterRuleSpec.groovy
validation/src/test/groovy/io/micronaut/validation/routes/RequestBeanParameterRuleSpec.groovy

This PR adds new Bindable annotation @RequestBean. With this annotation you can bind all request bindable values to one object. Example:
```
@Controller('/rest')
static class MyController {
@Get("/{pathVariable}{?queryValue}")
String getQueryValue(@RequestBean Bean bean) {
return "Some result"
}
@Getter
@AllArgsConstructor
@Introspected
static class Bean {
@Nullable
@QueryValue
String queryValue
@PathVariable
String pathVariable
@Nullable
@Header("some-header")
String header
}
} 
```
Motivation:
I was testing some Jax-rs application with Micronaut and noticed that there is no construct that is equal to `@BeanParams`. You can use exploded query params, but that is not the same. And in case you move some Jax-rs application to Micronaut and you are heavy user of `@BeanParams` this might not …

Add support for @RequestBean

---

inject-java/src/test/groovy/io/micronaut/event/DeadlockProducer.java
inject-java/src/test/groovy/io/micronaut/event/PublishPostConstructThreadSpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/event/ApplicationEventPublisher.java

Provides solution for #3124 
The actual problem is not solvable because a lock is placed on the bean registry to avoid duplicate singletons being created so removing this lock would break correctness. 
However the issue can be resolved by looking up the event listeners before firing events. This change adds an API to do that and provides a solution for this use case.
Debatable whether it should go into 1.3.x or not.

Provide API and solution sending events async 

---

inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
inject-java/src/main/java/io/micronaut/annotation/processing/visitor/LoadedVisitor.java
inject-java/src/test/groovy/io/micronaut/visitors/AllElementsVisitor.java
inject-java/src/test/groovy/io/micronaut/visitors/ClassElementSpec.groovy
inject-java/src/test/groovy/io/micronaut/visitors/ControllerGetVisitor.java

https://github.com/micronaut-projects/micronaut-core/issues/3065
Potential fix.
Scan enclosed elements in type hierarchy and discards method overrides.

Issue #3065 - TypeElementVisitor visits classes that have not the required annotation

---

core/src/main/java/io/micronaut/core/convert/ErrorsContext.java
http-client/src/test/groovy/io/micronaut/http/client/docs/binding/BookControllerTest.java
http-client/src/test/groovy/io/micronaut/http/client/rxjava2/RxHttpPostSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/ParameterBindingSpec.groovy
http-server/src/main/java/io/micronaut/http/server/binding/RequestArgumentSatisfier.java
runtime/src/main/java/io/micronaut/jackson/bind/JacksonBeanPropertyBinder.java
runtime/src/main/java/io/micronaut/jackson/bind/MapToObjectConverter.java
runtime/src/test/groovy/io/micronaut/jackson/bind/JacksonBeanPropertyBinderSpec.groovy

This provides a fix for #2919 
Note however it could be regarded as a breaking change since the previous implementation validated `null` values, however this was consistent with the way JSON was bound (which doesn't do this) and really is the job of the `validation` module. I had to alter the tests to take into account this new behaviour.

Make binding of form data consistent with JSON. Fixes #2919

---

http-client/src/test/groovy/io/micronaut/http/client/convert/GenericsJacksonSerdeSpec.groovy
http-client/src/test/resources/logback.xml
runtime/src/main/java/io/micronaut/jackson/convert/JsonNodeToObjectConverter.java
runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java

Fixes #3187
Had to copy the actual generic types from the value instantiator into the modified one for bean introspection module.
Also `JsonNodeToObjectConverter` was not using generics correctly. 
Note that adding `@Introspected` to https://github.com/micronaut-projects/micronaut-core/pull/3199/files#diff-a278a480adceba1b934e269cb01fa8a2R65
Makes the test fail so we don't seem to support `@JsonValue` types correctly either, but that is a different bug that may be worth a bug report.

Correctly use generics in bean introspections. Fixes #3187

---

runtime/src/main/java/io/micronaut/reactive/rxjava2/converters/RxJavaConverterRegistrar.java

Changed the conversion of Publisher to Maybe to use Flowable to allow support of the source emitting 0 items.  
In the current implementation, it uses `Single.fromPublisher(publisher)` which means that in case where the publisher emits 0 items, the Single will throw:
```
java.util.NoSuchElementException: The source Publisher is empty
```
For a Maybe - it's valid that the source can be empty.

Changed Publisher to Maybe Conversion to use Flowable

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/FileTypeHandler.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java

Otherwise headers added by filters are lost.

Copy headers from original response when returning not modified.

---

http-server/src/main/java/io/micronaut/http/server/cors/CorsFilter.java

as the headers are case insensitive by nature then also comparing the allowed headers should be case insensitive

make CORS headers case insensitive

---

discovery-client/src/main/resources/META-INF/native-image/io.micronaut.discovery/oraclecloud/native-image.properties

Fixes the Oracle client warning in #3294. The other warning is handled in https://github.com/micronaut-projects/micronaut-core/pull/3311

Remove GraalVM warning about OracleCloudVaultConfigurationClient

---

http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextFilter.java
http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextInstrumentation.java
http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextInvocationInstrumenter.java
tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec.groovy

The problem is a bit more complicated, MdcInstrumenter needs to be used all the time and reset context if somebody modified it. 
If somebody is setting MDC outside of MdcInstrumenter begin/after it will stay bound to the thread.

Clean MDC context, Fixes #3106

---

tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec.groovy
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec2.groovy

@graemerocher I could not reproduce [this failure](https://github.com/micronaut-projects/micronaut-core/runs/699190252?check_suite_focus=true#step:7:1462), but analysing the logs how it failed I added some extra tracing to better see what might have gone wrong when the trace_id is not found. I am only creating this PR as a draft hoping that build will still be triggered. Since it surfaces randomly we might need to trigger the build multiple times, is that possible?

Add tracing where MDCSpecs randomly fail

---

tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec.groovy
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec2.groovy
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MdcInstrumenterSpec.groovy
tracing/src/test/resources/logback.xml

Follow-up to #3322 and #3298 to investigate random failure of MDCSpec: verbose logging added to find out how MDC gets cleared between the filter and the controller.

MDCSpec: more detailed tracing

---

core/src/main/java/io/micronaut/core/reflect/ReflectionUtils.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/BasicAuthArgumentBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/CompletableFutureBodyBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/MaybeBodyBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/ObservableBodyBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/PublisherBodyBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/SingleBodyBinder.java
http/src/main/java/io/micronaut/http/bind/DefaultRequestBinderRegistry.java
http/src/main/java/io/micronaut/http/bind/binders/TypedRequestArgumentBinder.java
inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
runtime/src/main/java/io/micronaut/retry/intercept/RecoveryInterceptor.java
session/src/main/java/io/micronaut/session/binder/OptionalSessionArgumentBinder.java
session/src/main/java/io/micronaut/session/binder/SessionArgumentBinder.java

- Eliminate reflection usages in RequestArgumentBinder/RecoveryInterceptor
- Remove use of getAllInterfaces from BeanContext. Issue #3251

Removes reflection usages. Fixes #3251

---

tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MdcInstrumenterSpec.groovy

@graemerocher @lgathy Fixes master test fails.
Long story short tracing caused MDC context to me empty instead of null and caused MdcInstrumenter to always clean it.

Fix MDC context cleanup

---

http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextFilter.java
http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextInstrumentation.java
http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextInvocationInstrumenter.java
tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec.groovy
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec2.groovy
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MdcInstrumenterSpec.groovy

Related PRs: #3313 #3314 and #3328
@graemerocher As discussed earlier, backporting this to 1.3.x seems straightforward.
@dstepanov In relation to the fix in #3328 I was wondering if we would need an `MDC.clear()` on the `else` branch in `MdcInstrumenter.beforeInvocation()` symmetric to `afterInvocation()`? I could see this to be a problem when the executing thread already has data in MDC but our instrumented invocation requires MDC to be empty.

Backported dstepanov's solution to fix issue #3106

---

http-client/src/test/groovy/io/micronaut/http/client/aop/RequestBeanSpec.groovy
http/src/main/java/io/micronaut/http/annotation/RequestBean.java
http/src/main/java/io/micronaut/http/bind/binders/RequestBeanAnnotationBinder.java
src/main/docs/guide/httpServer/binding.adoc
validation/src/main/java/io/micronaut/validation/routes/rules/RequestBeanParameterRule.java

I extended functionality of RequestBean so it supports binding also typed values. 
Now you can bind any typed value like BasicAuth, Authorization or any custom type to single POJO (previously there was just support for HttpRequest and values with `@Bindable` annotation).

RequestBean supports binding also Typed Values now

---

inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesInnerClassSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/MyConfigInner.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/BeanIntrospectionSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigPropertiesInnerClassSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/MyConfigInner.java
inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
inject/src/main/java/io/micronaut/inject/beans/visitor/IntrospectedTypeElementVisitor.java

Notable changes:
* `isInnerConfiguration` now checks for a bean definition that has the annotation
* Type element visitors now visit the contents of inner classes. Previously only `visitClass` was called.
* The annotation metadata for type element visitors for inner classes now represents the metadata of the inner class instead of its owner
Closes https://github.com/micronaut-projects/micronaut-core/issues/3303

Configprops innerclass

---

core/src/main/java/io/micronaut/core/reflect/GenericTypeUtils.java
core/src/test/groovy/io/micronaut/core/reflect/GenericTypeUtilsSpec.groovy

So that the most specific interface will be first.
See Issue#238 in micronaut-openapi
https://github.com/micronaut-projects/micronaut-openapi/issues/238

Use LinkedHashSet in GenericTypeUtils.getAllGenericInterfaces()

---

runtime/src/main/java/io/micronaut/scheduling/instrument/MultipleInvocationInstrumenter.java
test-suite-kotlin/build.gradle
test-suite-kotlin/src/test/kotlin/io/micronaut/scheduling/instrument/MultipleInvocationInstrumenterSpec.kt

@graemerocher @lgathy I have removed the mutable state from `MultipleInvocationInstrumenter` it was only there to prevent `after` to be called in a case when an exception is thrown during `begin` which we can just ignore.
It would be better to refactor again to something like:
- capture context = InvocationInstrumenter
- try catch = set/restore context

Prevent parallel invocation instrumentation 2

---

management/src/main/java/io/micronaut/management/endpoint/EndpointDefaultConfiguration.java

This makes it possible to have "endpoints.all.port: null" in property source.

EndpointDefaultConfiguration port should be nullable

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataWriterSpec.groovy
inject/src/main/java/io/micronaut/inject/processing/JavaModelUtils.java
inject/src/test/groovy/io/micronaut/inject/annotation/AnnotationMetadataSpec.groovy

Handle class arrays in annotation metadata

---

http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java

Avoid ConcurrentModificationException in NettyMutableHttpResponse.getBody by using ConcurrentLinkedHashMap instead of lInkedHashMap.
Issue Details: https://github.com/micronaut-projects/micronaut-core/issues/3537

Avoid sync issue in getBody

---

core/src/main/java/io/micronaut/core/type/ReturnType.java
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/InterfaceConfigurationPropertiesSpec.groovy
runtime/src/main/java/io/micronaut/runtime/context/env/ConfigurationIntroductionAdvice.java

Previously, returning an `Optional` type in immutable / interface config would cause failures if the property did not exist
This PR amends the behavior to return `Optional.empty()` in the event the property does not exist similar to how `@Nullable` will cause it to return `null`

Support `Optional` in interface config

---

src/main/docs/guide/introduction/upgrading.adoc

In case for maven group id renaming for micronaut jdbc dependencies, the group was renamed from configuration to sql.

Added another example for maven group id renaming

---

inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/UnresolvedProvider.java
runtime/src/main/java/io/micronaut/scheduling/async/AsyncInterceptor.java

- Reduced bean lookup in `AsyncInterceptor`
- Removed extra step for `Flowable` it should be enough to use `subscribeOn`
- Provider impl. can use `BeanDefinition` to resolve the instance and cache it if it's a singleton

Improve Async and Provider performance

---

core/src/main/java/io/micronaut/core/convert/format/MapFormat.java

This won't have any impact on any functionality because the current logic doesn't read the default value. The change is to reflect the current default behavior

Change @MapFormat keyConvention default

---

runtime/build.gradle

Before v2 those dependencies were accessible in the user code.

Define Jackson Java 8 libs as API dependencies

---

src/main/docs/guide/ioc.adoc

Swaps `net.ltgt.apt` for `com.diffplug.eclipse.apt` in guide.
According to [the plugin repo](https://github.com/tbroyer/gradle-apt-plugin), the `net.ltgt.apt` plugin is now obsolete in Gradle versions >= 5.2.  
`com.diffplug.eclipse.apt` is still suggested for Eclipse projects and is brought in on launch projects.

Updates suggested apt plugin

---

parent/build.gradle

In Maven this is the preferred way because it allows any user of the pom parent to change the version simply overwriting the property in their own pom.xml

Set plugin versions using Maven properties

---

parent/build.gradle

Maven properties are used, so the user of the pom parent can easily override them in their own pom.xml
`jdk.version` property is set to 1.8 because this is the lower JDK compatibility supported by Micronaut at this moment.
The next used properties are supported officially by Maven:
- maven.compiler.source
- maven.compiler.target
- maven.compiler.release
- project.build.sourceEncoding
- project.reporting.outputEncoding

Set sensible defaults in the pom parent

---

src/main/docs/guide/cloud/serviceDiscovery/serviceDiscoveryConsul.adoc

The documentation suggests that "only" consul 1.2 works with micronaut (actually meaning "1.2 or newer"). As other documentation parts about consul also do not reference any version, it might be just removed from the documentation.

Remove consul version

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/ssl/CertificateProvidedSslBuilder.java

Prioritize HTTP/2 over HTTP/1.1 when certificate is provided. Fixes #3299

---

runtime/src/main/java/io/micronaut/retry/intercept/RecoveryInterceptor.java

I have noticed RecoveryInterceptor is called for all methods, PR caches some of the extractions and is able to skip it on the next call, not sure if MethodExecutionHandle is cacheable.
The other solution would be to set some boolean into context.setAttribute indicating that there is no fallback.
Should the execution of the fallback happen in a separate thread?

RecoveryInterceptor performance improvement

---

core/src/main/java/io/micronaut/core/io/socket/SocketUtils.java

This might help out with #3670 
Currently, `SocketUtils` considers a port available if an attempt to connect to it fails.  This isn't always the case.  For example, a timeout might indicate that something is using the port but did not respond to the connection in time.  I'm sure there are other situations where an exception might mean that the port is not available.
I'm not convinced that what I've proposed is actually the best approach here, but I think it is more correct than what we have now.  I believe that a port that isn't in use will always throw a`java.net.ConnectException` with a message of "Connection refused".  
I was thinking that it may be more conclusive to try to listen on the port, or maybe listen and send a short message through to determine if it is actually available, …

SocketUtils considers a port available if a ConnectException is thrown during connect attempt

---

src/main/docs/guide/aop/retry.adoc

Hi there.
I thought this retry behaviour differs from the documentation mentioning `with a delay of 1 second between each retry`. 
Actually the delay is gonna be increased exponentially.
The is the source code multiplying with 'attemptsNumber'
https://github.com/micronaut-projects/micronaut-core/blob/f8e0497b7cdb334c04d99ff8d7443571e9b64b27/runtime/src/main/java/io/micronaut/retry/intercept/SimpleRetry.java#L159
Test code mentions it's exponential
https://github.com/micronaut-projects/micronaut-core/blob/f8e0497b7cdb334c04d99ff8d7443571e9b64b27/runtime/src/test/groovy/io/micronaut/retry/intercept/SimpleRetryInstanceSpec.groovy#L66
Thanks.

SimpleRetry behaviour differs from the document

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java

Fixes #3777
Previously redirects, and other 3xx and 4xx, responses caused the HTTP
connection to be closed, which uses up too many TCP connections and
generally hurts performance.

Only close http connection for 500 errors

---

inject-java/src/test/groovy/io/micronaut/aop/CombinedBean.java
inject-java/src/test/groovy/io/micronaut/aop/CombinedBeanSpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

Fixes #3721
I think this is a left over artifact from https://github.com/micronaut-projects/micronaut-core/pull/2728
The bean definition reference `requiresProcessing` will return true if there is at least one method with `@Executable`, however not all methods should be subject to executable method processing (AOP for example). Before when all executable methods had `@Executable`, that condition wasn't possible so this wasn't an issue.

Skip non executable methods for processing instead of throwing an error

---

src/main/docs/guide/ioc/beanConfigurations.adoc

It seems that "INFO:" does not render into any notice box as "NOTE:" does.

Replace "INFO:" with "NOTE:" to show a notice box

---

http-client/src/test/groovy/io/micronaut/http/client/ClientHostNameSpec.groovy

Error message returned for ClientHostNameSpec are different in windows

Fixing ClientHost test for Windows

---

inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/ProviderUtils.java

Looks like there is one more problem with "Recursive update" update in 2.0.1
```
java.lang.IllegalStateException: Recursive update
at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1760)
at io.micronaut.context.DefaultBeanContext.getScopedBeanForDefinition(DefaultBeanContext.java:2316)
at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2298)
at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2270)
at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1240)
at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:1013)
at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1889)
... 74 …
```

Fix "Recursive update" for scoped proxies

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy

This is a proposed fix for the following problem (the problem started in 2.0.0 when PropertyCatalog.NORMALIZED was added, but the null check on normalized wasn't there like for the entries, so it caused this problem):
Keycloak or jboss wildfly had a system property who's name is something like [foo]=... and in PropertySourcePropertyResolver, any key that contains [ is assumed to have a property name before, which in this case is null... so it crashes with:
```
java.lang.NullPointerException
at io.micronaut.context.env.PropertySourcePropertyResolver.processPropertySource(PropertySourcePropertyResolver.java:539)
at io.micronaut.context.env.DefaultEnvironment.readPropertySources(DefaultEnvironment.java:399)
at io.micronaut.context.env.DefaultEnvironment.start(DefaultEnvironment.java:243)
at …
```

Fix PropertySourcePropertyResolver.java when property key starts with [.

---

runtime/src/main/resources/META-INF/native-image/io.micronaut/runtime-graal/native-image.properties

Enabling flag GraalvM `--install-exit-handlers` flag breaks AWS Lambda native-image support. Reverting the change.
See https://github.com/oracle/graal/issues/2742

Revert "Enable GraalMV `--install-exit-handlers`. Fixes #3880 (#3881)"

---

src/main/docs/guide/languageSupport/graal/graalFAQ.adoc

If you want to set the heap's maximum size in a native image, you could easily get an `OutOfMemoryError`, coming from Netty's `PooledByteBufAllocator`. The issue can be tackled by configuring Netty through the image's entrypoint, and it worth to mention in the FAQ section of the docs IMO.

Add details about Netty's memory management config

---

management/src/main/java/io/micronaut/management/endpoint/loggers/LoggersEndpoint.java
management/src/test/groovy/io/micronaut/management/endpoint/loggers/LoggersEndpointConfigurationSpec.groovy

Fixes #3925
The documentation states clearly that the endpoint is disabled by default: https://docs.micronaut.io/latest/guide/index.html#loggersEndpoint

Loggers endpoint is not enabled by default

---

inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/RecConf.java
inject-java/src/test/resources/application-rec1.yml
inject-java/src/test/resources/application-rec2.yml
runtime/src/main/java/io/micronaut/jackson/convert/JacksonConverterRegistrar.java

There should be some refactoring of properties processing so keys processing in Jackson registrar is not needed, this PR just fixed cases when kebab case properties were resolved as nulls.

Correct inconsistent mapping of camelCase vs kebab-case properties

---

src/main/docs/guide/httpServer/runningSpecificPort.adoc

if you have a micronaut.server.port in src/**main**/resources/application.yml and use a classpath scanning build tool like gradle, only the first test (starting up the embedded server) will succeed, all consecutive tests will fail with `Unable to start Micronaut server on port: xxxx` and `Address already in use`

explicitly setting random port in application-test.yml

---

inject-java-test/src/test/groovy/io/micronaut/inject/visitor/ElementAnnotateSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/visitor/AbstractJavaElement.java

Resolves #4008 
This fix makes sure the updated annotation metadata is stored in the modified cache under the same key it is retrieved later on.
This PR also includes a test verifying the annotation is correctly added.

Fix for method argument annotation visitors.

---

src/main/docs/guide/httpServer/reactiveServer.adoc

New Tomcat versions can handle multiple connections with the same thread (NIO threads), the correct is thread per request model.

Update Tomcat thread model

---

aop/build.gradle
aop/src/main/java/io/micronaut/aop/InterceptedMethod.java
aop/src/main/java/io/micronaut/aop/internal/intercepted/CompletionStageInterceptedMethod.java
aop/src/main/java/io/micronaut/aop/internal/intercepted/InterceptedMethodUtil.java
aop/src/main/java/io/micronaut/aop/internal/intercepted/KotlinInterceptedMethod.java
aop/src/main/java/io/micronaut/aop/internal/intercepted/PublisherInterceptedMethod.java
aop/src/main/java/io/micronaut/aop/internal/intercepted/SynchronousInterceptedMethod.java
aop/src/main/kotlin/io/micronaut/aop/util/CompletableFutureContinuation.kt
core/src/main/java/io/micronaut/core/async/publisher/Publishers.java
core/src/main/java/io/micronaut/core/type/Argument.java
core/src/main/java/io/micronaut/core/type/ReturnType.java
core/src/main/java/io/micronaut/core/util/KotlinUtils.java
function-client/src/main/java/io/micronaut/function/client/aop/FunctionClientAdvice.java
http-client-core/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
http-client/src/test/groovy/io/micronaut/http/client/aop/StreamSpec.groovy
runtime/src/main/java/io/micronaut/retry/intercept/DefaultRetryInterceptor.java
runtime/src/main/java/io/micronaut/retry/intercept/RecoveryInterceptor.java
runtime/src/main/java/io/micronaut/scheduling/async/AsyncInterceptor.java
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendClient.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendController.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendControllerSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/suspend/SuspendService.kt
tracing/src/main/java/io/micronaut/tracing/interceptor/TraceInterceptor.java
validation/src/main/java/io/micronaut/validation/ValidatingInterceptor.java
websocket/src/main/java/io/micronaut/websocket/interceptor/ClientWebSocketInterceptor.java

Added util classes to work with Kotlin's suspend functions in `MethodInterceptor`s and implemented to use it with `@Retryable`.
It should be possible to implement other interceptors like https://github.com/micronaut-projects/micronaut-cache/issues/183.
Personally I'm not a Kotlin user just found it interesting.

Add API to make it easier to write method interceptors and support Kotlin suspend functions
