micronaut-projects/micronaut-core

src/main/docs/guide/cli/createProject.adoc

Not sure if I got all the options included -- is "spek" an option also?

Update "test" CLI description for "create-function"

---

http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java
http/src/test/groovy/io/micronaut/http/uri/UriMatchTemplateSpec.groovy

URI with trailing slash should match a route without trailing slash

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/TypeElementVisitorTransform.groovy
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/utils/AstAnnotationUtils.groovy
inject-groovy/src/main/resources/META-INF/services/org.codehaus.groovy.transform.ASTTransformation
inject-groovy/src/test/groovy/io/micronaut/inject/visitor/CustomVisitorSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject-java/src/main/resources/META-INF/services/javax.annotation.processing.Processor
inject-java/src/test/groovy/io/micronaut/support/Parser.java
inject-java/src/test/groovy/io/micronaut/visitors/CustomVisitorSpec.groovy
inject/src/main/java/io/micronaut/inject/visitor/TypeElementVisitor.java

to achieve consistency across implementations

Extract execution of type visitors into their own transform classes

---

configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/jvm/JvmMeterRegistryBinder.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/logging/LogbackMeterRegistryBinder.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/system/SystemMeterRegistryBinder.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/binder/web/WebMeterRegistryFilter.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/management/endpoint/MetricsEndpoint.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/MeterRegistryCreationListener.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/MeterRegistryFactory.java
configurations/micrometer-core/src/main/java/io/micronaut/configuration/metrics/micrometer/SimpleMeterRegistryEventListener.java
configurations/micrometer-core/src/test/groovy/io/micronaut/configuration/metrics/management/endpoint/FilteredMetricsEndpointSpec.groovy
configurations/micrometer-registry-atlas/src/main/java/io/micronaut/configuration/metrics/micrometer/atlas/AtlasConfigurationProperties.java
configurations/micrometer-registry-atlas/src/main/java/io/micronaut/configuration/metrics/micrometer/atlas/AtlasMeterRegistryFactory.java
configurations/micrometer-registry-graphite/src/main/java/io/micronaut/configuration/metrics/micrometer/graphite/GraphiteConfigurationProperties.java
configurations/micrometer-registry-graphite/src/main/java/io/micronaut/configuration/metrics/micrometer/graphite/GraphiteMeterRegistryFactory.java
configurations/micrometer-registry-prometheus/src/main/java/io/micronaut/configuration/metrics/micrometer/prometheus/PrometheusConfigurationProperties.java
configurations/micrometer-registry-prometheus/src/main/java/io/micronaut/configuration/metrics/micrometer/prometheus/PrometheusMeterRegistryFactory.java
configurations/micrometer-registry-statsd/src/main/java/io/micronaut/configuration/metrics/micrometer/statsd/StatsdConfigurationProperties.java
configurations/micrometer-registry-statsd/src/main/java/io/micronaut/configuration/metrics/micrometer/statsd/StatsdMeterRegistryFactory.java

I haven't been able to get a failure again with the current code.  Will keep running while build is going.

Metrics cleanup

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/secret/SecretSignature.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/secret/SecretSignatureConfiguration.java
security-jwt/src/test/groovy/io/micronaut/docs/base64/JwtBase64Spec.groovy
src/main/docs/guide/security/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSignature.adoc

Closes: https://github.com/micronaut-projects/micronaut-core/issues/288

Allows to specify the secret base64 encoded

---

src/main/docs/guide/httpServer/staticResources.adoc

change router.static.resources to micronaut.router.static.resources

config path add micronaut

---

spring/src/main/java/io/micronaut/spring/beans/MicronautBeanProcessor.java
spring/src/test/groovy/io/micronaut/spring/beans/MicronautBeanProcessorByAnnotationTypeSpec.groovy
spring/src/test/groovy/io/micronaut/spring/beans/MicronautBeanProcessorByConcreteTypeSpec.groovy
src/main/docs/guide/ioc/springBeans.adoc

I am working on a Grails plugin which relies on these improvements.

Spring bean improvements

---

src/main/docs/guide/cloud/clientSideLoadBalancing.adoc

Corrected one work in clientSideLoadBalancing.adoc

Corrected grammar

---

src/main/docs/guide/cli/profiles/comparingVersions.adoc
src/main/docs/guide/toc.yml

Close: https://github.com/micronaut-projects/micronaut-core/issues/338

Docs micronaut-profiles-versions

---

inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
spring/build.gradle
spring/src/test/groovy/io/micronaut/spring/tx/TransactionalBean.java

Fixes https://github.com/micronaut-projects/micronaut-core/issues/345

Ensure the java annotation processor only runs once

---

management/src/main/java/io/micronaut/management/endpoint/EndpointDefaultConfiguration.java
management/src/main/java/io/micronaut/management/endpoint/processors/AbstractEndpointRouteBuilder.java
management/src/main/java/io/micronaut/management/endpoint/processors/DeleteEndpointRouteBuilder.java
management/src/main/java/io/micronaut/management/endpoint/processors/ReadEndpointRouteBuilder.java
management/src/main/java/io/micronaut/management/endpoint/processors/WriteEndpointRouteBuilder.java
management/src/test/groovy/io/micronaut/management/endpoint/EndpointsBasePathSpec.groovy
src/main/docs/guide/management/buildingEndpoints/endpointConfiguration.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/369

Enable configuration of endpoints' base path

---

gradle.properties
src/main/docs/guide/httpServer/datavalidation.adoc
src/main/docs/guide/toc.yml
validation/src/test/groovy/io/micronaut/docs/datavalidation/params/EmailController.java
validation/src/test/groovy/io/micronaut/docs/datavalidation/params/EmailControllerSpec.groovy
validation/src/test/groovy/io/micronaut/docs/datavalidation/pogo/Email.java
validation/src/test/groovy/io/micronaut/docs/datavalidation/pogo/EmailController.java
validation/src/test/groovy/io/micronaut/docs/datavalidation/pogo/EmailControllerSpec.groovy

Close: https://github.com/micronaut-projects/micronaut-core/issues/252

Doc Data Validation at controllers

---

security/src/test/groovy/io/micronaut/docs/security/authentication/AuthenticationProviderUserPassword.groovy
security/src/test/groovy/io/micronaut/docs/security/authentication/UserController.groovy
security/src/test/groovy/io/micronaut/docs/security/authentication/UserControllerSpec.groovy
security/src/test/groovy/io/micronaut/docs/security/principalparam/AuthenticationProviderUserPassword.groovy
security/src/test/groovy/io/micronaut/docs/security/principalparam/UserController.groovy
security/src/test/groovy/io/micronaut/docs/security/principalparam/UserControllerSpec.groovy
src/main/docs/guide/security/retrievingAuthenticatedUser.adoc
src/main/docs/guide/toc.yml

Close: https://github.com/micronaut-projects/micronaut-core/issues/399

Doc - Retrieve the authenticated user

---

discovery-client/src/main/java/io/micronaut/discovery/kubernetes/KubernetesDiscoveryClient.java

Updating to newer language features.

Change for loop to stream

---

src/main/docs/guide/cli/features.adoc

[#330] update features.adoc for jrebel, kafka, picocli and springloaded typo

[#330] update features.adoc for jrebel, kafka, picocli and springloaded typo

---

src/main/docs/guide/languageSupport/groovy.adoc

Close https://github.com/micronaut-projects/micronaut-core/issues/393
cc @ZacharyKlein

Docs - Embeed Micronaut Groovy Singleton Video

---

security/src/test/groovy/io/micronaut/security/corspreflightrequest/CorsPreflightRequestSpec.groovy

This is a test to verify the behaviour achieved with: https://github.com/micronaut-projects/micronaut-core/commit/8ac97399181d00d1f742c5c457c16479c8d60e82
Closes: https://github.com/micronaut-projects/micronaut-core/issues/418

Test - Cors Preflight Request

---

configurations/picocli/src/main/java/io/micronaut/configuration/picocli/PicocliRunner.java

[#330] improvement: add PicocliRunner to allow reducing boilerplate in generated code
This PR needs https://github.com/micronaut-projects/micronaut-profiles/pull/54

[#330] improvement: add PicocliRunner to allow reducing boilerplate in generated code

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy
src/main/docs/guide/cloud/serviceDiscovery/serviceDiscoveryConsul.adoc
src/main/docs/guide/config/propertySource.adoc

Adding new random property for uuid, uuid, and shortuuid.  Adding docs for random properties and additional information about consul instance id.
Also a bit of cleanup

Docs and Properties

---

inject-groovy/src/test/groovy/io/micronaut/docs/config/mapFormat/Engine.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/mapFormat/EngineConfig.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/mapFormat/EngineImpl.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/mapFormat/Vehicle.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/mapFormat/VehicleSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/properties/Engine.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/properties/EngineConfig.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/properties/EngineImpl.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/properties/VehicleSpec.groovy
src/main/docs/guide/config/configurationProperties.adoc

Docs and a simple test case for binding map properties with `@MapFormat`

@MapFormat docs

---

http-server-netty/src/test/groovy/io/micronaut/docs/respondingnotfound/BooksController.java
http-server-netty/src/test/groovy/io/micronaut/docs/respondingnotfound/BooksSpec.groovy
src/main/docs/guide/httpServer/respondingnotfound.adoc
src/main/docs/guide/toc.yml

Close: https://github.com/micronaut-projects/micronaut-core/issues/442

Doc - Simple 404 responses with null or Maybe.empty()

---

build.gradle
gradle.properties

Close: https://github.com/micronaut-projects/micronaut-core/issues/475

Adds Gradle plugin to check HTML sanity of Docs

---

src/main/docs/guide/cli/features.adoc

Fix typo in features doc section

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/HttpResponseSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/java/ResponseController.java
http/src/main/java/io/micronaut/http/HttpResponse.java

Add method to respond with body and location and 201

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/RegexBindingSpec.groovy
http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java

Fixes: https://github.com/micronaut-projects/micronaut-core/issues/535

If URI variable regex stars with ^, remove it

---

configurations/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/HibernateTransactionManagerFactory.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/C.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/C1.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/C2.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/CFactory.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/CFactoryReplacement.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/D.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/D1.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/D2.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/DFactory.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/DFactoryMethodReplacement.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/ReplacesSpec.groovy
inject-java/src/test/java/io/micronaut/docs/replaces/BookFactory.java
inject-java/src/test/java/io/micronaut/docs/replaces/CustomBookFactory.java
inject-java/src/test/java/io/micronaut/docs/replaces/MockBookService.java
inject-java/src/test/java/io/micronaut/docs/replaces/ReplacesTest.java
inject-java/src/test/java/io/micronaut/docs/replaces/TextBook.java
inject-java/src/test/java/io/micronaut/docs/replaces/TextBookFactory.java
inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/annotation/Replaces.java
inject/src/main/java/io/micronaut/inject/BeanDefinition.java
src/main/docs/guide/ioc/replaces.adoc

Replaces improvement

---

gradle.properties
inject/build.gradle
inject/src/main/java/io/micronaut/context/env/DefaultPropertyPlaceholderResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy

Fixed: Resolving Environment Variables with numbers

---

core/src/main/java/io/micronaut/core/annotation/AnnotationValueBuilder.java
security/build.gradle
security/src/main/java/io/micronaut/security/PermitAllAnnotationMapper.java
security/src/main/java/io/micronaut/security/RolesAllowedAnnotationMapper.java
security/src/main/resources/META-INF/services/io.micronaut.core.annotation.AnnotationMapper
security/src/test/groovy/io/micronaut/docs/security/securityRule/permitall/AuthenticationProviderUserPassword.groovy
security/src/test/groovy/io/micronaut/docs/security/securityRule/permitall/ExampleController.java
security/src/test/groovy/io/micronaut/docs/security/securityRule/permitall/PermitAllSpec.groovy
security/src/test/groovy/io/micronaut/docs/security/securityRule/secured/ExampleController.java
security/src/test/groovy/io/micronaut/security/permitall/BookController.groovy
security/src/test/groovy/io/micronaut/security/permitall/LanguagesController.groovy
security/src/test/groovy/io/micronaut/security/permitall/PermitAllSpec.groovy
security/src/test/groovy/io/micronaut/security/permitalloverridesrolesallowed/BookController.groovy
security/src/test/groovy/io/micronaut/security/permitalloverridesrolesallowed/PermitAllOverridesRolesAllowedSpec.groovy
security/src/test/groovy/io/micronaut/security/rolesallowed/AuthenticationProviderUserPassword.groovy
security/src/test/groovy/io/micronaut/security/rolesallowed/BookController.groovy
security/src/test/groovy/io/micronaut/security/rolesallowed/RolesAllowedSpec.groovy
src/main/docs/guide/security/securityRule/secured.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/561

Support @PermitAll and @RolesAllowed

---

src/main/docs/resources/css/custom.css
src/main/docs/resources/style/layout.html
src/main/docs/resources/style/page.html

Close: https://github.com/micronaut-projects/micronaut-core/issues/595

[docs] don’t print navigation elements

---

gradle/docs.gradle
http-client/src/test/groovy/io/micronaut/http/client/docs/binding/BookController.java
http-client/src/test/groovy/io/micronaut/http/client/docs/binding/BookControllerTest.java
http/src/main/java/io/micronaut/http/uri/UriMatchVariable.java
src/main/docs/guide/httpServer/routing.adoc
validation/build.gradle
validation/src/main/java/io/micronaut/validation/async/AsyncTypeElementVisitor.java
validation/src/main/java/io/micronaut/validation/async/package-info.java
validation/src/main/java/io/micronaut/validation/routes/RouteParameterElement.java
validation/src/main/java/io/micronaut/validation/routes/RouteValidationResult.java
validation/src/main/java/io/micronaut/validation/routes/RouteValidationVisitor.java
validation/src/main/java/io/micronaut/validation/routes/package-info.java
validation/src/main/java/io/micronaut/validation/routes/rules/MissingParameterRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/NullableParameterRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/RouteValidationRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/package-info.java
validation/src/main/java/io/micronaut/validation/websocket/WebSocketVisitor.java
validation/src/main/java/io/micronaut/validation/websocket/package-info.java
validation/src/main/resources/META-INF/services/io.micronaut.inject.visitor.TypeElementVisitor
validation/src/test/groovy/io/micronaut/validation/routes/MissingParameterRuleSpec.groovy
validation/src/test/groovy/io/micronaut/validation/routes/NullableParameterRuleSpec.groovy

Closes https://github.com/micronaut-projects/micronaut-core/issues/383

Organize validators. Add new route argument validator

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/java/ParameterBindingSpec.groovy
router/src/main/java/io/micronaut/web/router/AnnotatedMethodRouteBuilder.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/531

route starting with /{?

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/NettyCompletedFileUpload.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/multipart/NettyStreamingFileUpload.java
test-suite/src/test/groovy/io/micronaut/docs/client/upload/MultipartFileUploadSpec.groovy
test-suite/src/test/groovy/io/micronaut/upload/StreamUploadSpec.groovy
test-suite/src/test/groovy/io/micronaut/upload/UploadController.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/625

call fileUpload.length()

---

security/src/main/java/io/micronaut/security/annotation/DenyAllAnnotationMapper.java
security/src/main/java/io/micronaut/security/rules/SecuredAnnotationRule.java
security/src/main/java/io/micronaut/security/rules/SecurityRule.java
security/src/main/resources/META-INF/services/io.micronaut.inject.annotation.AnnotationMapper
security/src/test/groovy/io/micronaut/security/denyall/AuthenticationProviderUserPassword.groovy
security/src/test/groovy/io/micronaut/security/denyall/BookController.groovy
security/src/test/groovy/io/micronaut/security/denyall/DenyAllSpec.groovy
src/main/docs/guide/security/securityRule/secured.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/570

[security]  support javax.annotation.security.DenyAll

---

core/src/main/java/io/micronaut/core/annotation/AnnotationValueBuilder.java

One notable addition is support for nested AnnotationValue in the builder.

Support more types in AnnotationValueBuilder

---

configurations/hibernate-validator/build.gradle

Upgrade hibernate-validator to 6.0.13.Final

---

security/src/main/java/io/micronaut/security/authentication/Authenticator.java
src/main/docs/guide/appendix/breaks.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/649
Close: https://github.com/micronaut-projects/micronaut-core/pull/646

Authenticator::authenticate(AuthenticationRequest

---

http/src/main/java/io/micronaut/http/HttpHeaders.java
http/src/test/groovy/io/micronaut/http/HttpHeadersSpec.groovy

Close: https://github.com/micronaut-projects/micronaut-core/issues/652

HttpHeaders.accept() should return List<MediaType> for comma separated string

---

security/src/main/java/io/micronaut/security/authentication/providers/DelegatingAuthenticationProvider.java
security/src/main/java/io/micronaut/security/token/propagation/TokenPropagationConfigurationProperties.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/644

Improve extendability of DelegatingAuthenticationProvider

---

http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/BookController.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/ExceptionHandlerSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/OutOfStockException.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/OutOfStockExceptionHandler.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/aterrorexceptionhandlerprecedence/AtErrorExceptionHandlerPrecedenceSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/aterrorexceptionhandlerprecedence/BookController.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/aterrorexceptionhandlerprecedence/OutOfStockController.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/aterrorexceptionhandlerprecedence/OutOfStockException.java
http-server-netty/src/test/groovy/io/micronaut/docs/http/server/exception/aterrorexceptionhandlerprecedence/OutOfStockExceptionHandler.java
src/main/docs/guide/httpServer/errorHandling.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/665

Document ExceptionHandler

---

security-jwt/build.gradle
security-jwt/src/main/java/io/micronaut/security/token/jwt/generator/JwtTokenGenerator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/SignatureConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/SignatureGeneratorConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignature.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureGenerator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureGeneratorConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/ec/ECSignatureGeneratorFactory.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/rsa/RSASignature.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/rsa/RSASignatureConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/rsa/RSASignatureGenerator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/rsa/RSASignatureGeneratorConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/rsa/RSASignatureGeneratorFactory.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/secret/SecretSignature.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/secret/SecretSignatureConfiguration.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/secret/SecretSignatureFactory.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsa/PS512RSASignatureConfiguration.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsa/SignRSANotEncrypSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/AuthenticationProviderUserPassword.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/Book.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/BooksClient.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/BooksController.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/BooksRsaSignatureConfiguration.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/GatewayBooksController.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/GatewayRsaSignatureConfiguration.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/rsagenerationvalidation/TwoServicesOneSignWithRsaOneVerfiesWithRsaSpec.groovy
src/main/docs/guide/appendix/breaks.adoc
src/main/docs/guide/security/authenticationStrategies/jwt/jwtGenerator/jwtGeneratorSignature.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/688

 Split signature generator and verification

---

build.gradle
configurations/hibernate-gorm/build.gradle
configurations/hibernate-jpa/build.gradle
configurations/jdbc-dbcp/build.gradle
configurations/jdbc-hikari/build.gradle
configurations/jdbc-tomcat/build.gradle
configurations/multitenancy-gorm/build.gradle
gradle.properties
management/build.gradle
src/main/docs/guide/cloud/distributedTracing/zipkin.adoc
src/main/docs/guide/configurations/dataAccess/hibernateSupport.adoc
src/main/docs/guide/configurations/dataAccess/sqlSupport.adoc
test-suite/build.gradle
tracing/build.gradle

Add new dependencies to BOM to allow remove the explicit version from the profiles.
This PR must be merged with https://github.com/micronaut-projects/micronaut-profiles/pull/79

Add some dependencies to BOM

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/NettyHttpServerSpec.groovy

Simplest fix that will flip the default.

Fix #763 by looking at the protocol version.

---

configurations/hibernate-jpa/src/main/java/io/micronaut/configuration/hibernate/jpa/HibernateTransactionManagerFactory.java
configurations/jdbc-dbcp/src/test/groovy/io/micronaut/configuration/jdbc/dbcp/DatasourceFactorySpec.groovy
configurations/jdbc-tomcat/src/test/groovy/io/micronaut/configuration/jdbc/tomcat/DatasourceFactorySpec.groovy
jdbc/build.gradle
jdbc/src/main/java/io/micronaut/jdbc/spring/DataSourceTransactionManagerFactory.java
jdbc/src/main/java/io/micronaut/jdbc/spring/HibernatePresenceCondition.java
jdbc/src/main/java/io/micronaut/jdbc/spring/SpringDataSourceResolver.java
jdbc/src/main/java/io/micronaut/jdbc/spring/package-info.java
spring/build.gradle

This PR moves the Spring JDBC related classes to the JDBC module

Move Spring/JDBC related classes to jdbc module. Fixes #787

---

src/main/docs/guide/languageSupport/graal/graalServices.adoc

Document Graal support (RC7 and RC8) for Consul. Fixes #815
This needs to be merged with https://github.com/micronaut-projects/micronaut-profiles/pull/86

Document Graal support for Consul. Fixes #815

---

inject-java/build.gradle
inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertyNullableSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/foreach/SomeConfiguration.java
inject/src/main/java/io/micronaut/context/AbstractParametrizedBeanDefinition.java

correctly handles Nullable in parameterised beans. Fixes #833

Fix for Issue 833

---

inject/src/main/java/io/micronaut/context/env/AbstractPropertySourceLoader.java
inject/src/test/groovy/io/micronaut/context/env/yaml/YamlPropertySourceLoaderSpec.groovy

@graemerocher  It seems like the rebase was not working properly. So, I have created another PR with cherry-picking the changes from #845 for 1.0.x

(1.0.x) Fixed #758 Default database empty configuration is not working

---

session/src/main/java/io/micronaut/session/http/CookieHttpSessionIdGenerator.java
session/src/main/java/io/micronaut/session/http/CookieHttpSessionStrategy.java

To ease debugging and replacement.
See: https://github.com/micronaut-projects/micronaut-core/issues/882

Refactor CookieHttpSessionStrategy

---

src/main/docs/guide/languageSupport/graal/graalServices.adoc

include instructions about how to use DockerfileAllInOne 
see https://github.com/micronaut-projects/micronaut-profiles/pull/87

include DockerfileAllInOne

---

security/src/main/java/io/micronaut/security/endpoints/LogoutController.java
security/src/main/java/io/micronaut/security/endpoints/LogoutControllerConfiguration.java
security/src/main/java/io/micronaut/security/endpoints/LogoutControllerConfigurationProperties.java
security/src/test/groovy/io/micronaut/security/endpoints/LogoutControllerAllowedMethodsSpec.groovy

Close: https://github.com/micronaut-projects/micronaut-core/issues/848

Allow GET access to logout endpoint

---

security/src/main/java/io/micronaut/security/token/TokenAuthenticationFetcher.java
security/src/main/java/io/micronaut/security/token/reader/DefaultTokenResolver.java
security/src/main/java/io/micronaut/security/token/reader/TokenResolver.java
src/main/docs/guide/appendix/breaks.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/846

Extract token resolution to it is own class

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/HttpPostSpec.groovy
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java

Also support passing a charsequence body for url encoded content type

Fix issue with multiple params with the same name

---

inject/src/main/java/io/micronaut/context/annotation/AliasFor.java
inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java
management/src/main/java/io/micronaut/management/endpoint/annotation/Delete.java
management/src/main/java/io/micronaut/management/endpoint/annotation/Read.java
management/src/main/java/io/micronaut/management/endpoint/annotation/Write.java
src/main/docs/guide/management/buildingEndpoints/endpointMethod.adoc
test-suite/src/test/groovy/io/micronaut/docs/server/endpoints/CurrentDateEndpointSpec.groovy
test-suite/src/test/groovy/io/micronaut/docs/server/endpoints/MessageEndpoint.groovy
test-suite/src/test/groovy/io/micronaut/docs/server/endpoints/MessageEndpointSpec.groovy

Endpoint media type support. Add support for annotation name in aliasfor

---

discovery-client/src/test/groovy/io/micronaut/discovery/cloud/DigitalOceanMetadataResolverSpec.groovy
discovery-client/src/test/groovy/io/micronaut/discovery/cloud/digitalOceanInstanceMetadata.json
inject/src/main/java/io/micronaut/context/env/ComputePlatform.java
inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
inject/src/main/java/io/micronaut/context/env/Environment.java
runtime/src/main/java/io/micronaut/discovery/cloud/AbstractComputeInstanceMetadata.java
runtime/src/main/java/io/micronaut/discovery/cloud/ComputeInstanceMetadataResolverUtils.java
runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonComputeInstanceMetadataResolver.java
runtime/src/main/java/io/micronaut/discovery/cloud/aws/AmazonEC2InstanceMetadata.java
runtime/src/main/java/io/micronaut/discovery/cloud/digitalocean/DigitalOceanInstanceMetadata.java
runtime/src/main/java/io/micronaut/discovery/cloud/digitalocean/DigitalOceanMetadataConfiguration.java
runtime/src/main/java/io/micronaut/discovery/cloud/digitalocean/DigitalOceanMetadataKeys.java
runtime/src/main/java/io/micronaut/discovery/cloud/digitalocean/DigitalOceanMetadataResolver.java
runtime/src/main/java/io/micronaut/discovery/cloud/digitalocean/DigitalOceanNetworkInterface.java
runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeInstanceMetadata.java
runtime/src/main/java/io/micronaut/discovery/cloud/gcp/GoogleComputeInstanceMetadataResolver.java
src/main/docs/guide/cloud/cloudConfiguration.adoc

At the moment it supports the Instance Metadata API

Initial support for Digital Ocean compute platform

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/builder/EngineConfig.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/builder/EngineFactory.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/builder/EngineImpl.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/builder/SparkPlug.groovy
inject-groovy/src/test/groovy/io/micronaut/docs/config/builder/VehicleSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesBuilderSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesBuilderSpec.groovy

Fixed @ConfigurationBuilder does not work on method 

---

configurations/mongo-gorm/build.gradle
configurations/mongo-reactive/build.gradle

Bumping de.flapdoodle.embed.mongo version to 2.1.1

---

configurations/postgres-reactive/build.gradle
discovery-client/build.gradle
test-suite/build.gradle

That would solve #880 I guess. Giving it a try :nerd_face:

Bumping testcontainers version to 1.10.1

---

src/main/docs/guide/cloud/cloudConfiguration.adoc

missed brackets for link to DigitalOceanInstanceMetada source code

fix typo at DigitalOcean

---

src/main/docs/guide/cloud/cloudConfiguration.adoc

See: https://github.com/micronaut-projects/micronaut-core/pull/929

Explain cloud-specific configuration files

---

inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java

see: https://github.com/micronaut-projects/micronaut-core/pull/929

timeout digital ocean

---

inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java

Close: https://github.com/micronaut-projects/micronaut-core/pull/931

remove extra google compute check

---

session/src/main/java/io/micronaut/session/http/HttpSessionConfiguration.java
session/src/test/groovy/io/micronaut/session/http/CookieHttpSessionStrategySpec.groovy
src/main/docs/guide/appendix/breaks.adoc

see: https://github.com/micronaut-projects/micronaut-core/issues/882

Default cookie path

---

router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
router/src/test/groovy/io/micronaut/context/router/AnnotationRouteBuilderSpec.groovy

Change error route storage in default router to not use comparable

---

core/src/main/java/io/micronaut/core/reflect/ReflectionUtils.java
core/src/test/groovy/io/micronaut/core/reflect/ReflectionUtilsSpec.groovy

ReflectionUtils.findField() has a bug when trying to find a non-existent field.

Reflection issue

---

discovery-client/src/main/java/io/micronaut/discovery/eureka/EurekaConfiguration.java
discovery-client/src/test/groovy/io/micronaut/discovery/eureka/EurekaClientConfigSpec.groovy
src/main/docs/guide/cloud/serviceDiscovery/serviceDiscoveryEureka.adoc

* eureka instance application name, hostname, ip address and exposed
port can be now customized via configuration
* updated eureka related documentation
Closes #1021

Improved Eureka registration support

---

src/main/docs/guide/httpServer/views/thymeleaf.adoc
views/build.gradle

Updated to the latest Thymeleaf 3.0.11.RELEASE version

Update Thymeleaf to 3.0.11.RELEASE

---

http/src/main/java/io/micronaut/http/simple/SimpleHttpResponseFactory.java

fixes https://github.com/agorapulse/micronaut-libraries/issues/16

assigning the body to newly created request

---

core/src/main/java/io/micronaut/core/version/annotation/Version.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
router/src/main/java/io/micronaut/web/router/Router.java
router/src/main/java/io/micronaut/web/router/version/FilteredRouter.java
router/src/main/java/io/micronaut/web/router/version/RouteMatchesFilter.java
router/src/main/java/io/micronaut/web/router/version/RoutesVersioningConfiguration.java
router/src/main/java/io/micronaut/web/router/version/Version.java
router/src/main/java/io/micronaut/web/router/version/VersionedRouter.java
router/src/main/java/io/micronaut/web/router/version/VersionedRouterDecoratorConfiguration.java
router/src/main/java/io/micronaut/web/router/version/VersioningRouteMatchesFilter.java
router/src/main/java/io/micronaut/web/router/version/strategy/HeaderVersionExtractingStrategy.java
router/src/main/java/io/micronaut/web/router/version/strategy/ParameterVersionExtractingStrategy.java
router/src/main/java/io/micronaut/web/router/version/strategy/VersionExtractingStrategy.java
router/src/test/groovy/io/micronaut/web/router/DefaultFilterRouteSpec.groovy
router/src/test/groovy/io/micronaut/web/router/StaticResourceResolverSpec.groovy
router/src/test/groovy/io/micronaut/web/router/version/DefaultVersionedUrlFilterSpec.groovy
router/src/test/groovy/io/micronaut/web/router/version/VersionResolvingStrategiesConfigSpec.groovy
runtime/src/main/java/io/micronaut/cache/interceptor/CacheInterceptor.java
runtime/src/main/java/io/micronaut/discovery/registration/RegistrationConfiguration.java
runtime/src/main/java/io/micronaut/scheduling/io/watch/DefaultWatchThread.java
runtime/src/main/java/io/micronaut/scheduling/io/watch/MacOsWatchThread.java
runtime/src/main/java/io/micronaut/scheduling/io/watch/WatchServiceFactory.java
runtime/src/main/java/io/micronaut/scheduling/io/watch/event/FileChangedEvent.java
src/main/docs/guide/cli/reloading.adoc
src/main/docs/guide/cli/reloading/automaticRestart.adoc
src/main/docs/guide/toc.yml
src/main/docs/guide/whatsNew.adoc

Resolves the issue #997 
Version based routes matching.
If 'micronaut.router.versioning.enabled = false' - application behavior is the same.
Otherwise the DefaultRouter will be decorated to versioned router and check the provided version

Api versioning feature

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/consumes/ConsumesMatchesRouteSpec.groovy
router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java

@graemerocher On the fence as to whether this is a breaking change or not. Thoughts?
On second thought I don't think this is because its just changing where the check occurs.

Match routes on content type

---

src/main/docs/guide/commandLineApps/picocli/picocliQuickStart.adoc

@Client is not resolved because the import is wrong

wrong import

---

views/src/main/java/io/micronaut/views/ViewsFilterOrderProvider.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/1129

Make ViewsFilterOrderProvider public

---

cli/src/main/groovy/io/micronaut/cli/console/interactive/CandidateListCompletionHandler.java
cli/src/main/groovy/io/micronaut/cli/console/logging/MicronautConsole.java
cli/src/main/groovy/io/micronaut/cli/io/support/AntPathMatcher.java
cli/src/main/groovy/io/micronaut/cli/io/support/PathMatchingResourcePatternResolver.java
cli/src/main/groovy/io/micronaut/cli/io/support/ResourceUtils.java
core/src/main/java/io/micronaut/core/cli/CommandLineParser.java
core/src/main/java/io/micronaut/core/type/ReturnType.java
core/src/main/java/io/micronaut/core/type/TypeVariableResolver.java
core/src/main/java/io/micronaut/core/util/StringUtils.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/ObservableBodyBinder.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/binders/SingleBodyBinder.java
inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadata.java
management/src/main/java/io/micronaut/management/endpoint/refresh/RefreshEndpoint.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
runtime/src/main/java/io/micronaut/jackson/codec/JsonMediaTypeCodec.java

replace toArray(new T[size]) with toArray(new T[0]) for better performance

Optimize toArray (#1157)

---

http-client/src/test/groovy/io/micronaut/http/client/docs/basics/HelloControllerTest.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/1150

Showcase UriBuilder

---

gradle.properties
gradle/webdriverbinaries.gradle
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/cookie/JwtCookieAuthenticationSpec.groovy
security-session/src/test/groovy/io/micronaut/docs/security/session/SessionAuthenticationSpec.groovy
test-suite/src/test/groovy/io/micronaut/upload/browser/UploadBrowserSpec.groovy

Close: https://github.com/micronaut-projects/micronaut-core/issues/1163

Geb and parallel

---

security/src/main/java/io/micronaut/security/token/basicauth/BasicAuthTokenReaderConfigurationProperties.java
security/src/test/groovy/io/micronaut/security/token/basicauth/BasicAuthTokenValidatorSpec.groovy

Close: https://github.com/micronaut-projects/micronaut-core/issues/1160

use kebah-case for Basic auth prefix

---

src/main/docs/guide/languageSupport/graal/graalServices.adoc

This needs to be merged with: https://github.com/micronaut-projects/micronaut-profiles/pull/106

Update documentation to Graal RC12

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/validator/JwtTokenValidator.java

These methods did not exist in 1.0.x branch.

make JwtTokenValidator methods public

---

src/main/docs/guide/config/propertySource.adoc

Added note for validating config properties on startup. Tried this and it works in my local environment.

Update propertySource.adoc for validating properties on startup

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonContentProcessor.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/JsonBodyBindingSpec.groovy

Initialize jackson processor for single-type publisher arguments

---

tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java

I'm probably the least knowledgable person in this discussion but perhaps the one with the most time to contribute this :)
https://github.com/micronaut-projects/micronaut-core/issues/1049
Is there any way to write tests for this?

implement MdcInstrumenter according to comment from luckyswede

---

security-jwt/src/test/groovy/io/micronaut/docs/websockets/EchoClientWebSocket.groovy
security-jwt/src/test/groovy/io/micronaut/docs/websockets/EchoClientWebSocketSpec.groovy
security-jwt/src/test/groovy/io/micronaut/docs/websockets/EchoServerWebSocket.java
security-jwt/src/test/groovy/io/micronaut/docs/websockets/HomeController.groovy
security-jwt/src/test/groovy/io/micronaut/docs/websockets/HomePageSpec.groovy
security-jwt/src/test/groovy/io/micronaut/docs/websockets/MockAuthenticationProvider.java
security-jwt/src/test/groovy/io/micronaut/docs/websockets/ParamTokenReader.java
security-jwt/src/test/groovy/io/micronaut/docs/websockets/WebSocketsHomePage.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/websockets/EchoClientWebSocket.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/websockets/EchoServerWebSocket.java
security-jwt/src/test/groovy/io/micronaut/security/token/websockets/MockAuthenticationProvider.java
security-jwt/src/test/groovy/io/micronaut/security/token/websockets/ServerWebSocketOnOpenBindsHeaderSpec.groovy
security-jwt/src/test/resources/websockets/app.js
security-jwt/src/test/resources/websockets/style.css

Close: https://github.com/micronaut-projects/micronaut-core/issues/1292

Add websockets + security tests

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/JwkProvider.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/endpoints/KeysController.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/rsa/RSASignatureGenerator.java
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/endpoints/KeysControllerSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwksSpec.groovy
security-jwt/src/test/groovy/io/micronaut/security/token/jwt/signature/jwks/JwsSignatureSpec.groovy

`JwkProvider` does not exist in `1.0.x` branch.

return a list of JWK in JwkProvider

---

security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/DefaultJwkValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwkValidator.java
security-jwt/src/main/java/io/micronaut/security/token/jwt/signature/jwks/JwksSignature.java

`JwksSignature`. is not present in `1.0.x` branch.

Extract jwk validation to its own bean

---

core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java
core/src/test/groovy/io/micronaut/core/convert/DefaultConversionServiceSpec.groovy

Convert the result to appropriate Iterable for CharSequence -> Iterable.

#1338 Map properties from application.yml to Set

---

http-client/src/main/java/io/micronaut/http/client/multipart/AbstractFilePart.java
http-client/src/test/groovy/io/micronaut/http/client/HttpPostSpec.groovy

Resolve charset for AbstractFilePart from MediaType before adding default.

#1370 Support charset for multi-part request

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy

#1369 Fix IndexOutOfBoundsException while resolving application.properties

---

configurations/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiInheritedPojoControllerSpec.groovy

* Fixed StackOverflow error by breaking inheritance loop while generating schema definition.
* Improved empty allOf, anyOf and oneOf check.
* Tests for inheritance and StackOverflow error.
* Storing state "inProgressSchemas" in AbstractOpenApiVisitor.java for tracking in-progress schemas.

 #1385 Handle OpenAPI inheritance issue

---

inject-groovy/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/property/PropertyOnlyInject.java

Support creating beans that only have @Property in Java

---

discovery-client/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java

* fixed reading of application-specific configuration
* more intuitive parameter definition
* support for plain values with keys derived from the path
* removed dead code

AWS SMM Parameter Store Improvements

---

configurations/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiPojoControllerSpec.groovy

Please merge 1.0.x branch to master after closing this PR.

Handle Map in OpenAPI

---

http-server-netty/src/test/groovy/io/micronaut/web/router/version/VersionControllerSpec.groovy
router/src/main/java/io/micronaut/web/router/exceptions/DuplicateRouteException.java

This thrown a different exception when you had a controller

Keep uri routes in Duplicate Route Exception

---

discovery-client/src/test/groovy/io/micronaut/discovery/management/DiscoveryClientHealthIndicatorConfigurationSpec.groovy
management/src/main/java/io/micronaut/management/health/indicator/discovery/DiscoveryClientHealthIndicator.java
management/src/main/java/io/micronaut/management/health/indicator/discovery/DiscoveryClientHealthIndicatorConfiguration.java

Create per request from @jameskleeh

discovery client health indicator enable/disable via config

---

views/src/main/java/io/micronaut/views/ViewsFilter.java
views/src/main/java/io/micronaut/views/ViewsRenderer.java
views/src/main/java/io/micronaut/views/thymeleaf/EngineContextFactory.java
views/src/main/java/io/micronaut/views/thymeleaf/LinkBuilder.java
views/src/main/java/io/micronaut/views/thymeleaf/ThymeleafFactory.java
views/src/main/java/io/micronaut/views/thymeleaf/ThymeleafViewsRenderer.java
views/src/main/java/io/micronaut/views/thymeleaf/WebContext.java
views/src/main/java/io/micronaut/views/thymeleaf/WebEngineContext.java
views/src/test/groovy/io/micronaut/docs/ThymeleafViewRendererSpec.groovy
views/src/test/groovy/io/micronaut/docs/ViewsController.groovy
views/src/test/resources/views/home.html
views/src/test/resources/views/notFound.html
views/src/test/resources/views/relativeLink.html
views/src/test/resources/views/thymeleaf/index.html

See https://github.com/thymeleaf/thymeleaf/issues/458

Add support for thymeleaf context-relative urls

---

router/src/main/java/io/micronaut/web/router/version/RouteVersionFilter.java
router/src/main/java/io/micronaut/web/router/version/RoutesVersioningConfiguration.java
router/src/test/groovy/io/micronaut/web/router/version/DefaultVersionedUrlFilterSpec.groovy
src/main/docs/guide/httpServer/apiVersioning.adoc

Default version support

---

configurations/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy

Please merge the branch 1.0.x into master after closing this PR.

#1181 Handle OpenAPI @Content schema

---

configurations/openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationParseSpec.groovy

Please merge 1.0.x to master after closing this PR.

#1352 Handle openapi array schema

---

configurations/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiOperationCallbackSpec.groovy
function-client/src/main/java/io/micronaut/function/client/aop/FunctionClientAdvice.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/1464

For Open-API use @Header value if no name is specified

---

configurations/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiControllerVisitor.java
configurations/openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiControllerVisitorSpec.groovy

Close https://github.com/micronaut-projects/micronaut-core/issues/1474

Use default values for placeholders in openapi generation

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettyStreamedFileCustomizableResponseType.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/types/files/NettySystemFileCustomizableResponseType.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/resources/StaticResourceResolutionSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/types/FileTypeHandlerSpec.groovy

* Do not add both Content-Length and transfer-encoding: chunked.

#1462 Fixed transfer-encoding bug

---

security-jwt/src/test/groovy/io/micronaut/docs/jwks/JwksSpec.groovy
src/main/docs/guide/security/authenticationStrategies/jwt/jwtValidation/jwks.adoc
src/main/docs/guide/security/endpoints/keys.adoc
src/main/docs/guide/toc.yml
src/main/docs/guide/whatsNew.adoc

Close: https://github.com/micronaut-projects/micronaut-core/issues/1425

Document JWKS support

---

aop/build.gradle
buffer-netty/build.gradle
build.gradle
core/build.gradle
discovery-client/build.gradle
gradle/publishing.gradle
http-server/build.gradle
http/build.gradle
inject-groovy/build.gradle
inject-java/build.gradle
inject/build.gradle
messaging/build.gradle
runtime/build.gradle
session/build.gradle

The only change I'm not sure about is applying the plugin at the root level
Fixes #1485

Fix shadowjar configuration

---

security/src/test/groovy/io/micronaut/security/rules/InterceptUrlMapRuleSpec.groovy

While debugging on issue https://github.com/micronaut-projects/micronaut-core/issues/1511 I stumbled across the following test case that was initially hard for me to understand why code such as works. I guess the formatting gave me hard time here.
```
def rule = new InterceptUrlMapRule(new TokenConfiguration() {
@Override
String getRolesName() {
"roles"
}
}) {
@Override
protected List<InterceptUrlMapPattern> getPatternList() {
[new InterceptUrlMapPattern("/foo", ["ROLE_ADMIN"], HttpMethod.GET)]
}
}
```
The following PR provides a transformation of that code using Spock data driven approach and Spock mocks.

Make test more readable

---

src/main/docs/guide/management/providedEndpoints/infoEndpoint.adoc

- update gradle plugin version for Git Info Source
- suggest gradle versions plugin for Build info Source

Doc - InfoEndpoint

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/StreamRequestSpec.groovy

Fixes https://github.com/micronaut-projects/micronaut-core/issues/1548

Fix#1548 - Use equals rather than == to check contentType

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/AbstractCreateCommand.groovy

Close: https://github.com/micronaut-projects/micronaut-core/issues/1570
See: `11.14.2. ${COMPLETION-CANDIDATES} Variable` section.
https://picocli.info/#_show_default_values

Add {COMPLETION-CANDIDATES}

---

config/checkstyle/suppressions.xml
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/ValidatedGetterConfigurationSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ValidatedGetterConfig.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ValidatedGetterConfigurationSpec.groovy

This is technically a new feature but we have advertised it as working so I consider it a bug

Support validation on getter methods of @ConfigurationProperties

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
inject/src/main/java/io/micronaut/inject/qualifiers/ClosestTypeArgumentQualifier.java
inject/src/main/java/io/micronaut/inject/qualifiers/Qualifiers.java
inject/src/main/java/io/micronaut/inject/qualifiers/TypeArgumentQualifier.java
inject/src/test/groovy/io/micronaut/inject/qualifiers/ClosestTypeArgumentSpec.groovy

Fix exception handler retrieval bug

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/MalformedUriSpec.groovy

Remove once per request filters if the error came from netty

---

jdbc/src/main/java/io/micronaut/jdbc/JdbcDatabaseManager.java

This exception was not very informative for debugging, so I propose a small change.

More verbose exception for JDBC URL.

---

http-client/src/test/groovy/io/micronaut/http/client/CompressedRequest.groovy
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java

Fixes https://github.com/micronaut-projects/micronaut-core/issues/1384

Add HttpContentDecompressor to netty server

---

core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java
core/src/test/groovy/io/micronaut/core/convert/DefaultConversionServiceSpec.groovy
core/src/test/groovy/io/micronaut/core/convert/Status.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/1522

Bind enums with toString()

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/encoders/HttpResponseEncoder.java

Annotate HttpResponseEncoder and RoutingInBoundHandler with @Sharable.

Reuse sharable netty's handlers.

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorMissingArgumentSpec.groovy
router/src/main/java/io/micronaut/web/router/exceptions/UnsatisfiedRouteException.java
runtime/src/main/java/io/micronaut/scheduling/executor/DefaultExecutorSelector.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/1567

Better error for missing bindable

---

runtime/src/main/java/io/micronaut/scheduling/executor/DefaultExecutorSelector.java
src/main/docs/guide/httpClient/clientAnnotation/clientParameters.adoc
src/main/docs/guide/httpServer/routing.adoc
test-suite/src/test/groovy/io/micronaut/docs/server/routes/IssuesController.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/1691
Close: https://github.com/micronaut-projects/micronaut-core/pull/1710

Document @PathVariable

---

inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
inject/src/main/java/io/micronaut/context/env/EnvironmentPropertySource.java
inject/src/test/groovy/io/micronaut/context/env/EnvironmentPropertySourceSpec.groovy
runtime/src/main/java/io/micronaut/runtime/Micronaut.java
src/main/docs/guide/config/propertySource.adoc
test-suite-groovy/src/test/groovy/io/micronaut/docs/context/Application.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/context/Application.kt
test-suite/src/test/java/io/micronaut/docs/context/Application.java
test-suite/src/test/java/io/micronaut/docs/server/intro/Application.java

This is being targeted to 1.1.x because of the performance regression with many environment variables

Support finer control over environment variables

---

benchmarks/src/jmh/java/io/micronaut/context/env/PropertySourcePropertyResolverBenchmark.java
inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/EnvironmentPropertySourceSpec.groovy

Improve performance of environment properties

---

inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/H.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/HFactory.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/HImpl.java
inject-java/src/test/groovy/io/micronaut/inject/qualifiers/replaces/ReplacesSpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

Allow factory beans to replace beans that have AOP advice applied. 

---

inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/beans/IntrospectionSpec.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/ioc/beans/Manufacturer.kt
test-suite/src/test/java/io/micronaut/docs/ioc/beans/IntrospectionSpec.java
test-suite/src/test/java/io/micronaut/docs/ioc/beans/Manufacturer.java

Map `org.jetbrains.annotations.Nullable` to `javax.annotation.Nullable`.

#1703 Updated JavaMethodElement

---

gradle.properties

Upgrade some dependencies already released but not included in the bom.

Upgrade Micronaut dependencies

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/AbstractCreateCommand.groovy

Sort features alphabetically when autocompleting in the CLI

---

runtime/src/main/java/io/micronaut/health/HeartbeatDiscoveryClientCondition.java

This should prevent dependency loop shown in https://github.com/micronaut-projects/micronaut-flyway/issues/17

Lazier HeartbeatDiscoveryClientCondition

---

test-suite-kotlin/src/test/resources/logback.xml
validation/src/main/java/io/micronaut/validation/routes/RouteValidationVisitor.java
validation/src/main/java/io/micronaut/validation/routes/rules/MissingParameterRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/NullableParameterRule.java
validation/src/main/java/io/micronaut/validation/routes/rules/RouteValidationRule.java
validation/src/test/groovy/io/micronaut/validation/routes/NullableParameterRuleSpec.groovy

Change route validation nullable parameter rule to ignore clients

---

http/src/main/java/io/micronaut/http/HttpHeaderValues.java

See: https://tools.ietf.org/html/rfc7234#section-7.1.3

Add Cache directive constants to HttpHeaderValues

---

inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
inject/src/main/java/io/micronaut/context/env/Environment.java
inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy

Ability to remove property sources from the environment

Environment improvements

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
inject-groovy/src/test/groovy/io/micronaut/AbstractBeanDefinitionSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/validation/ValidatedParseSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/AbstractTypeElementSpec.groovy
inject/src/main/java/io/micronaut/inject/annotation/AnnotationMetadataWriter.java
inject/src/main/java/io/micronaut/inject/annotation/DefaultAnnotationMetadata.java
inject/src/main/java/io/micronaut/inject/beans/visitor/BeanPropertyWriter.java
test-suite-groovy/src/test/groovy/io/micronaut/docs/ioc/validation/custom/DurationPatternValidatorSpec.groovy
validation/src/test/groovy/io/micronaut/validation/validator/pojo/FavoriteWebsSpec.groovy
validation/src/test/groovy/io/micronaut/validation/validator/pojo/ValidURLs.java

Issue 1813

---

src/main/docs/resources/css/custom.css
src/main/docs/resources/js/guide.js
src/main/docs/resources/style/layout.html

Supports persistence and OS theme detection

Add dark theme to the documentation

---

src/main/docs/guide/ioc.adoc

Developers not using micronaut-cli are often not aware of `testAnnotationProcessor`.

testAnnotationProcessor

---

inject-java/src/test/groovy/io/micronaut/inject/context/RegisterSingletonSpec.groovy
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

fixed ClassCastException when retrieving bean

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy

Fixes https://github.com/micronaut-projects/micronaut-core/issues/1942

Fix property parsing

---

http/src/main/java/io/micronaut/http/uri/UriTemplate.java
http/src/test/groovy/io/micronaut/http/uri/UriTemplateSpec.groovy

See: https://github.com/micronaut-projects/micronaut-core/issues/1932

Prevent UriTemplate from creating empty GET params when null

---

inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy

Remove internally created property sources on close

---

test-suite/src/test/java/io/micronaut/docs/context/annotation/primary/Green.java

Be consistent with groovy and kotlin code.

Fix docs: The Primary Bean

---

core/src/main/java/io/micronaut/core/convert/DefaultConversionService.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/binding/ParameterBindingSpec.groovy
runtime/src/main/java/io/micronaut/discovery/ServiceInstance.java

Add logic for unwrapping arrays

---

http-client/src/test/groovy/io/micronaut/http/client/HttpPostSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/HttpPutSpec.groovy
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/docs/consumes/TestController.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/consumes/ConsumesMatchesRouteSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/consumes/RouteComplexitySpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/errors/ErrorSpec.groovy
http/src/main/java/io/micronaut/http/uri/UriTemplate.java
http/src/test/groovy/io/micronaut/http/uri/UriMatchTemplateSpec.groovy
router/src/main/java/io/micronaut/web/router/AbstractRouteMatch.java
router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
router/src/main/java/io/micronaut/web/router/RouteMatch.java
router/src/main/java/io/micronaut/web/router/Router.java
router/src/main/java/io/micronaut/web/router/UriRoute.java
router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java

Fixes https://github.com/micronaut-projects/micronaut-core/issues/1303 and https://github.com/micronaut-projects/micronaut-core/issues/1971

Routing improvements

---

aop/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
inject-java/src/test/groovy/io/micronaut/aop/Logged.java
inject-java/src/test/groovy/io/micronaut/aop/LoggedInterceptor.java
inject-java/src/test/groovy/io/micronaut/aop/named/NamedAopAdviceSpec.groovy
inject-java/src/test/groovy/io/micronaut/aop/named/NamedFactory.java
inject-java/src/test/groovy/io/micronaut/aop/named/OtherBean.java
inject-java/src/test/groovy/io/micronaut/aop/named/OtherInterface.java
inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
inject/src/main/java/io/micronaut/context/BeanResolutionContext.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/DefaultBeanResolutionContext.java

Graeme - I understand the issue behind #1927 and there are several ways forward. I'm creating this PR that contains a failing test so we can discuss when you get back.

Add test for issue #1927

---

runtime/src/main/java/io/micronaut/scheduling/NextFireTime.java
runtime/src/main/java/io/micronaut/scheduling/ReschedulingTask.java
runtime/src/main/java/io/micronaut/scheduling/ScheduledExecutorTaskScheduler.java

https://github.com/micronaut-projects/micronaut-core/issues/2061
Add a check to see if the task have been fired before its fire time.

Fix for #2061 - Task may have fired too early.

---

session/src/main/java/io/micronaut/session/http/CookieHttpSessionStrategy.java
session/src/main/java/io/micronaut/session/http/HttpSessionConfiguration.java
session/src/test/groovy/io/micronaut/session/http/CookieHttpSessionStrategySpec.groovy

Adds config property to secure cookie.

---

inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/PackageConfigurationInjectProcessor.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject-java/src/main/resources/META-INF/gradle/incremental.annotation.processors

This initial PR resolves #2019 and adds support for Gradle incremental annotation processing. However I am not sure if it is correct and need to verify with some Gradle experts

Support for incremental annotation processing. Fixes #2019

---

validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
validation/src/test/groovy/io/micronaut/validation/validator/pojo/PojoBodyParameterSpec.groovy

I'm not sure about the fix but the idea is to get BeanIntrospector from the argument value instance instead of the declared type.

Validation should support inheritance

---

src/main/docs/guide/management/providedEndpoints.adoc

- incorrect path
- parenthesis

Fix ThreadDumpEndPoint documentation

---

inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

resubmitting #2151 against `1.2.x`

added missing checks for presence of bean definitions

---

src/main/docs/guide/httpServer/routing.adoc

Document non-standard http #2167

---

src/main/docs/guide/management/buildingEndpoints/endpointAnnotation.adoc
src/main/docs/guide/management/buildingEndpoints/endpointMethod.adoc

Fixes micronaut-projects/micronaut-docs#13.

Update link to @Endpoint API doc in endpointAnnotation.adoc

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java

issue #2253: correct handling of cancelled flowable emitter

---

src/main/docs/guide/languageSupport/graal/graalServices.adoc

I was doing the guide and figured that I'll update what is missing or wrong.
Thanks for this awesome project!

Update getting started with graal (docs)

---

src/main/docs/guide/aop/introductionAdvice.adoc
src/main/docs/guide/httpClient/clientAnnotation/clientParameters.adoc
src/main/docs/guide/httpServer/binding.adoc
src/main/docs/guide/httpServer/reactiveServer.adoc
src/main/docs/guide/httpServer/statusAnnotation.adoc

few corrections to wording as I read through the docs

doc grammar corrections

---

http/src/main/java/io/micronaut/http/uri/UriTemplate.java
http/src/test/groovy/io/micronaut/http/uri/UriTemplateSpec.groovy

fix for issue-2325
in UriTemplate.expand() reset anyPreviousHasContent when we reach query parameters.
https://github.com/micronaut-projects/micronaut-core/issues/2325

Issue 2325 - UriTemplate and optional query parameters

---

core/src/main/java/io/micronaut/core/async/publisher/Publishers.java
core/src/main/java/io/micronaut/core/util/ArgumentUtils.java

Fixed inefficiencies in ArgumentUtils

---

http/src/main/java/io/micronaut/http/MediaType.java

MediaType: compute and cache toString() value in constructor

---

core/src/main/java/io/micronaut/core/naming/NameUtils.java
core/src/test/groovy/io/micronaut/core/naming/NameUtilsSpec.groovy

Fixed NameUtils.decapitalize

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/consumes/ConsumesMatchesRouteSpec.groovy

Verifies https://github.com/micronaut-projects/micronaut-core/issues/2334 is resolved.
The issue was fixed with with https://github.com/micronaut-projects/micronaut-core/pull/2349

Test consumes=all accepts any body regardless of content-type

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
inject-groovy/src/test/groovy/io/micronaut/ast/groovy/annotation/Child.groovy
inject-groovy/src/test/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilderSpec.groovy
inject-groovy/src/test/groovy/io/micronaut/ast/groovy/annotation/Parent.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java

Fixes micronaut-projects/micronaut-openapi#23

Properly set annotation values to be an array if the type is an array

---

build.gradle

I didn't think about this yesterday unfortunately..

Added micronaut-cache-noop to the Micronaut managed versions

---

cli/src/main/groovy/io/micronaut/cli/io/support/MavenBuildTokens.groovy

This will solve both https://github.com/micronaut-projects/micronaut-core/issues/2031 and https://github.com/micronaut-projects/micronaut-core/issues/2302 by applying the suggested fix of re-ordering the annotation process when generating an cli application with the maven build option.

Issue 2031+2302

---

src/main/docs/guide/httpClient/clientAnnotation.adoc

Addresses https://github.com/micronaut-projects/micronaut-core/issues/2274

Added note about @Produces and @Consumes semantics

---

http-client/src/test/groovy/io/micronaut/http/client/docs/streaming/HeadlineController.java
test-suite-groovy/src/test/groovy/io/micronaut/docs/sse/HeadlineController.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/streaming/HeadlineController.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/sse/HeadlineController.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/streaming/HeadlineController.kt
test-suite/src/test/java/io/micronaut/docs/sse/HeadlineController.java
test-suite/src/test/java/io/micronaut/docs/streaming/HeadlineController.java

https://github.com/micronaut-projects/micronaut-core/issues/2274

Replace usage of processes with produces

---

router/src/main/java/io/micronaut/web/router/Router.java

Fixed checkstyle

---

tracing/src/main/java/io/micronaut/tracing/instrument/util/MdcInstrumenter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MdcInstrumenterSpec.groovy

#2312 MDC propagation to ExecutorService

---

router/src/main/java/io/micronaut/web/router/resource/StaticResourceResolver.java
router/src/test/groovy/io/micronaut/web/router/StaticResourceResolverSpec.groovy

https://github.com/micronaut-projects/micronaut-core/issues/2436
static resource resolver does not honnor server context path.

Fix for Issue #2436

---

http-client/src/main/java/io/micronaut/http/client/NettyClientHttpRequest.java
http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java
http/src/main/java/io/micronaut/http/MutableHttpRequest.java
http/src/main/java/io/micronaut/http/MutableHttpResponse.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpRequest.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpResponse.java
http/src/main/java/io/micronaut/http/simple/cookies/SimpleCookies.java
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/BindingController.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/BindingControllerTest.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/BindingController.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/BindingControllerTest.kt
test-suite/src/test/java/io/micronaut/docs/server/binding/BindingController.java
test-suite/src/test/java/io/micronaut/docs/server/binding/BindingControllerTest.java

Resolves https://github.com/micronaut-projects/micronaut-core/issues/2361

Add cookies method to set multiple cookies on a request

---

router/src/main/java/io/micronaut/web/router/Router.java
validation/src/main/java/io/micronaut/validation/validator/DefaultConstraintDescriptor.java
validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
validation/src/main/java/io/micronaut/validation/validator/IntrospectedBeanDescriptor.java
validation/src/test/groovy/io/micronaut/validation/validator/ValidatorSpec.groovy

Once receiving ConstraintViolationException raised by  default validator the annotation information is lost.

ConstraintViolationException is missing annotation information with default validator.

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java

Use String.replace instead of String.replaceAll as

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/jackson/TestModel.groovy
runtime/src/main/java/io/micronaut/jackson/modules/BeanIntrospectionModule.java
runtime/src/test/groovy/io/micronaut/jackson/modules/BeanIntrospectionModuleSpec.groovy

Fix : BeanIntrospectionModule should honour @JsonView

---

inject/src/main/java/io/micronaut/context/AbstractExecutableMethod.java
validation/src/main/java/io/micronaut/validation/ValidatingInterceptor.java
validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
validation/src/test/groovy/io/micronaut/validation/Foo.java
validation/src/test/groovy/io/micronaut/validation/ValidatedSpec.groovy

Validate method return value

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/ProfileInfoCommand.groovy

updated the profile info command, executing `mn profile-info base` will result in the following where included features are denoted with a +
```
| => mn profile-info base
| Profile: base
--------------------
The base profile
| Provided Commands:
--------------------
create-bean        Creates a singleton bean
create-job         Creates a job with scheduled method
create-repository  Creates a repository and associated test
create-test        Creates a simple test for the project's testing framework
help               Prints help information for a specific command
| Provided Features:
| (+) denotes features included by default.
--------------------
annotation-api (+)        Adds Java annotation API
application               Facilitates creating an executable JVM application and adds support …
```

Issue 1774

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/ServerRedirectSpec.groovy

#2258 Copy headers from original request to redirect request

---

http-client/src/main/java/io/micronaut/http/client/interceptor/HttpClientIntroductionAdvice.java
http-client/src/test/groovy/io/micronaut/http/client/HttpGetSpec.groovy

… exploded query params
Fixes #2498

Fix issue with exploded query params and QueryValue annotation

---

runtime/src/main/java/io/micronaut/cache/AbstractMapBasedSyncCache.java

Fixes https://github.com/micronaut-projects/micronaut-cache/issues/32

SyncCache implementation for providers that implement the Map interface

---

test-suite-groovy/src/test/groovy/io/micronaut/docs/server/json/PersonController.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/json/PersonController.kt
test-suite/src/test/java/io/micronaut/docs/server/json/PersonController.java

I found this potential mistake in the docs. Please verify and merge if legit.

Fix documentation: missing global attribute on Error annotation

---

CONTRIBUTING.md

Add space to header to have it rendered properly

Fix md format typo in CONTRIBUTING.md

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
management/src/test/groovy/io/micronaut/management/endpoint/EndpointsPortSpec.groovy
router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
router/src/main/java/io/micronaut/web/router/Router.java
router/src/main/java/io/micronaut/web/router/UriRoute.java
router/src/main/java/io/micronaut/web/router/filter/FilteredRouter.java

Ensure routes don't listen to custom ports if not explicitly configured to

---

core/src/main/java/io/micronaut/core/naming/NameUtils.java
core/src/test/groovy/io/micronaut/core/naming/NameUtilsSpec.groovy
inject/src/test/groovy/io/micronaut/context/env/yaml/YamlPropertySourceLoaderSpec.groovy
inject/src/test/resources/application-spaces.yml

Hyphenate should replace spaces as well

---

http/src/main/java/io/micronaut/http/uri/UriTemplate.java
http/src/test/groovy/io/micronaut/http/uri/UriTemplateSpec.groovy

and expanded segment contains OPERATOR_NONE.

Fix UrlTemplate expand where operator is OPERATOR_NONE and

---

.github/workflows/corretto.yml

Amazon Corretto support

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonContentProcessor.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/jackson/JsonHttpContentSubscriberFactory.java
runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java
runtime/src/test/groovy/io/micronaut/jackson/parser/JacksonProcessorSpec.groovy

Issue https://github.com/micronaut-projects/micronaut-core/issues/2618
Try to respect DeserializationConfig in incremental jackson parser.
Check if DeserializationFeature.USE_BIG_DECIMAL_FOR_FLOATS and DeserializationFeature.USE_BIG_INTEGER_FOR_INTS are enabled.

fix: Precision lost on BigDecimal

---

management/src/main/java/io/micronaut/management/endpoint/info/source/BuildInfoSource.java
management/src/main/java/io/micronaut/management/endpoint/info/source/GitInfoSource.java

Fixes https://github.com/micronaut-projects/micronaut-aws/issues/45.

Remove @Refreshable from InfoSources that won't change at runtime

---

http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java

This change was already in [PR 2635](https://github.com/micronaut-projects/micronaut-core/pull/2635) but that PR was closed by @jameskleeh

allow ServerCookieEncoder to be changed

---

http-server/src/main/java/io/micronaut/http/server/HttpServerConfiguration.java

Fix http server timeouts documentation

---

http-netty/src/main/java/io/micronaut/http/netty/NettyMutableHttpResponse.java
http/src/main/java/io/micronaut/http/simple/SimpleHttpResponse.java

Fixes https://github.com/micronaut-projects/micronaut-aws/issues/105

Introspecting subtypes of MutableHttpResponse

---

management/src/main/java/io/micronaut/management/health/aggregator/RxJavaHealthAggregator.java

We are conducting a research project on re-ordering Stream APIs for improving program execution speed.
We measured execution time of target Stream before and after re-ordering.
The result is :
```
the order of Stream API      running time
===============================================
distinct().sorted()                 2ms
sorted().distinct()                 1ms
```

Re-ordering Stream APIs

---

function-client/src/main/java/io/micronaut/function/client/aws/AWSLambdaAsyncClientFactory.java

Fixes https://github.com/micronaut-projects/micronaut-aws/issues/64

Remove @Refreshable, since it would prevent to be used in a function environment

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/context/NoPackageSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/context/NoPackageSpec.groovy

Improve error message for beans defined in the default package

---

src/main/docs/guide/languageSupport/graal/graalServices.adoc

This PR needs to be merged with https://github.com/micronaut-projects/micronaut-profiles/pull/231

Remove 'graal-native-image-kotlin' from docs

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/DataStreamSpec.groovy

Support Publisher<ByteBuffer> for client bodies and fix read timeout on codec exception

---

inject-groovy/src/test/groovy/io/micronaut/inject/foreach/EachPropertySpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertyNullableSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/foreach/EachPropertySpec.groovy
inject/src/main/java/io/micronaut/context/DefaultApplicationContext.java
src/main/docs/guide/appendix/breaks.adoc
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MdcInstrumenterSpec.groovy

Throw exception for single injection of non primary @Each

---

cli/src/main/groovy/io/micronaut/cli/profile/commands/AbstractCreateCommand.groovy

Fixes:
* https://github.com/micronaut-projects/micronaut-test/issues/90
* https://github.com/micronaut-projects/micronaut-test/issues/109

Applying feature evictions

---

src/main/docs/guide/languageSupport/graal/graalServices.adoc

I noticed what seems like a small typo in the Graal section of the docs ;)

chore: fix typo

---

core/src/main/java/io/micronaut/core/convert/format/MapFormat.java
inject-groovy/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/MapProperties.java
inject-java/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
src/main/docs/guide/appendix/breaks.adoc
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/property/ConfigProps.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/inject/property/MapFormatSpec.kt

Map format changes

---

websocket/src/main/java/io/micronaut/websocket/WebSocketBroadcaster.java
websocket/src/main/java/io/micronaut/websocket/WebSocketSession.java

In reference to issue [2834](https://github.com/micronaut-projects/micronaut-core/issues/2834)

Update Javadocs for websocket send and broadcast methods

---

http-client/src/main/java/io/micronaut/http/client/DefaultHttpClient.java
http-client/src/main/java/io/micronaut/http/client/NettyClientHttpRequest.java
http-client/src/test/groovy/io/micronaut/http/client/netty/NettyClientHttpRequestSpec.groovy
http-netty/src/main/java/io/micronaut/http/netty/AbstractNettyHttpRequest.java
http-netty/src/main/java/io/micronaut/http/netty/NettyHttpParameters.java
http/src/main/java/io/micronaut/http/uri/DefaultUriBuilder.java
http/src/main/java/io/micronaut/http/uri/UriBuilder.java

Fix bug with getParameters in mutable requests

---

src/main/docs/guide/httpServer/websocket/websocketClient.adoc
src/main/docs/guide/httpServer/websocket/websocketServer.adoc

fix a few documentation issues on WebSockets, add notes on use of send, sendAsync, sendSync and corresponding broadcast methods

Update WebSocket guide description

---

http/src/main/java/io/micronaut/http/HttpResponseFactory.java

Fixes very minor javadoc typo in HttpResponseFactory

---

discovery-client/src/main/java/io/micronaut/discovery/aws/parameterstore/AWSParameterStoreConfigClient.java
http/src/main/java/io/micronaut/http/uri/UriTemplate.java

when argument is not a regexp.

Replace String.replaceAll with String.replace

---

http/src/main/java/io/micronaut/http/MediaType.java
http/src/test/groovy/io/micronaut/http/MediaTypeSpec.groovy

so that it can be compressed when served.

Add yaml as text based media type

---

bom/profiles.properties
build.gradle
gradle.properties

This needs to be merged with https://github.com/micronaut-projects/micronaut-profiles/pull/246

Add servlet dependencies to BOM

---

runtime/src/main/java/io/micronaut/cache/graal/CacheSubstitutions.java

Fixes https://github.com/micronaut-projects/micronaut-security/issues/197

Improve support for GraalVM and cache

---

inject-java/src/test/groovy/io/micronaut/inject/annotation/BeanDefinitionAnnotationMetadataSpec.groovy
inject-java/src/test/resources/logback.xml
inject/src/main/java/io/micronaut/context/AbstractBeanDefinition.java
inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
inject/src/main/java/io/micronaut/context/BeanContextConfiguration.java
inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/inject/BeanDefinitionReference.java
inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java
inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionReferenceWriter.java
inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
src/main/docs/guide/introduction/whatsNew.adoc

Support eager init of beans

---

config/checkstyle/checkstyle.xml
http-client-core/src/main/java/io/micronaut/http/client/filter/ClientFilterResolutionContext.java
http-client-core/src/main/java/io/micronaut/http/client/filter/DefaultHttpClientFilterResolver.java
http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
http-client/src/main/java/io/micronaut/http/client/netty/RxNettyHttpClientRegistry.java
http-client/src/test/groovy/io/micronaut/http/client/ClientScopeSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/filter/ClientFilterStereotypeSpec.groovy
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/interceptor/HttpFilterSpec.groovy
http/src/main/java/io/micronaut/http/filter/DefaultFilterEntry.java
http/src/main/java/io/micronaut/http/filter/HttpClientFilterResolver.java
http/src/main/java/io/micronaut/http/filter/HttpFilterResolver.java
http/src/main/java/io/micronaut/http/filter/HttpServerFilterResolver.java
inject/src/main/java/io/micronaut/context/BeanDefinitionDelegate.java
inject/src/main/java/io/micronaut/context/DefaultBeanContext.java
inject/src/main/java/io/micronaut/context/Qualifier.java
inject/src/main/java/io/micronaut/inject/BeanDefinition.java
router/src/main/java/io/micronaut/web/router/AnnotatedFilterRouteBuilder.java
router/src/main/java/io/micronaut/web/router/DefaultFilterRoute.java
router/src/main/java/io/micronaut/web/router/DefaultRouteBuilder.java
router/src/main/java/io/micronaut/web/router/DefaultRouter.java
router/src/main/java/io/micronaut/web/router/FilterRoute.java
router/src/main/java/io/micronaut/web/router/RouteBuilder.java

Refactor server filters to be registered and found more like client filters. 

---

build.gradle
gradle.properties
gradle/publishing.gradle
parent/build.gradle
settings.gradle
src/main/docs/guide/cli/createProject.adoc
src/main/docs/guide/cli/reloading/automaticRestart.adoc
src/main/docs/guide/cli/reloading/springloaded.adoc
src/main/docs/guide/introduction/whatsNew.adoc
src/main/docs/guide/quickStart/creatingServer.adoc
src/main/docs/guide/toc.yml

A parent POM that can used in Micronaut Maven projects. Fixes #2996

Maven Parent POM

---

validation/src/main/java/io/micronaut/validation/validator/constraints/DefaultConstraintValidators.java
validation/src/test/groovy/io/micronaut/validation/validator/ValidatorSpec.groovy

Fixes https://github.com/micronaut-projects/micronaut-core/issues/3013

Fix #3013 - Add size validator for Object array

---

http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
http-netty/src/main/java/io/micronaut/http/netty/channel/ChannelPipelineCustomizer.java
http-netty/src/main/java/io/micronaut/http/netty/channel/ChannelPipelineListener.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpServer.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/configuration/NettyHttpServerConfiguration.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/websocket/NettyServerWebSocketUpgradeHandler.java
runtime/src/main/java/io/micronaut/runtime/server/EmbeddedServer.java
src/main/docs/guide/httpServer/serverConfiguration/nettyPipeline.adoc
src/main/docs/guide/toc.yml
test-suite-groovy/build.gradle
test-suite-groovy/src/test/groovy/io/micronaut/docs/netty/LogbookPipelineCustomizer.groovy
test-suite-kotlin/build.gradle
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/netty/LogbookPipelineCustomizer.kt
test-suite/build.gradle
test-suite/src/test/groovy/io/micronaut/docs/netty/ChannelPipelineCustomizerSpec.groovy
test-suite/src/test/java/io/micronaut/docs/netty/LogbookPipelineCustomizer.java

Allow customization of the Netty pipeline for server/client. Fixes #2719

---

runtime/src/main/java/io/micronaut/runtime/context/scope/refresh/RefreshInterceptor.java
runtime/src/test/groovy/io/micronaut/runtime/context/scope/RefreshScopeSpec.groovy
runtime/src/test/groovy/io/micronaut/runtime/context/scope/refresh/RefreshInterceptorSpec.groovy

Don't load RefreshInterceptor in function and android environments.
Close: https://github.com/micronaut-projects/micronaut-core/issues/3072

Don't load RefreshInterceptor in function and android environments.

---

router/src/main/java/io/micronaut/web/router/DefaultRouter.java

Close: https://github.com/micronaut-projects/micronaut-core/issues/3080

fix: use path instead of uri

---

build.gradle

Add the 'junit-jupiter' bom dependency to Micronaut's bom
See https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-jupiter

 add junit-jupiter to dependency list

---

build.gradle
src/main/docs/guide/configurations/dataAccess.adoc
src/main/docs/guide/configurations/dataAccess/mysqlSupport.adoc
src/main/docs/guide/configurations/dataAccess/postgresSupport.adoc

See also https://github.com/micronaut-projects/micronaut-sql/pull/149

Fix references to reactive postgres module and add mysql module

---

build.gradle
gradle.properties

This is needed for SpringBoot and SpringWeb features in Starter

Add spring boot starter and start-web to the BOM.

---

src/main/docs/guide/multitenancy.adoc

I don't think the plural possessive is correct here.  I think "each" makes "tenant" singular.

Fix grammar

---

runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java
runtime/src/test/groovy/io/micronaut/jackson/parser/JacksonProcessorSpec.groovy

[Related issue](https://github.com/micronaut-projects/micronaut-core/issues/3133)

Fix whole numbers deserialisation in JacksonProcessor

---

inject-java/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/configproperties/MyConfig.java
runtime/src/main/java/io/micronaut/jackson/bind/MapToObjectConverter.java

Property with kebab case is missing in `@ConfigurationProperties` bean.

PR test bug report. Property with kebab case is missing in 1.3.5 (1.3.4 works)

---

build.gradle
gradle.properties
src/main/docs/guide/messaging/nats.adoc
src/main/docs/guide/toc.yml

- adds documentation for nats repository
- adds micronaut-nats to micronaut-bom
This PR waits for the release of micronaut-nats.

Integration with Nats.io

---

aop/src/main/java/io/micronaut/aop/writer/AopProxyWriter.java
inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/ConfigurationPropertiesBuilderSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/configuration/ConfigurationBuilderSpec.groovy
inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionVisitor.java
inject/src/main/java/io/micronaut/inject/writer/BeanDefinitionWriter.java
inject/src/main/java/io/micronaut/inject/writer/ConfigBuilderState.java

Support interfaces for configuration builders

---

validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
validation/src/main/java/io/micronaut/validation/validator/constraints/ConstraintValidator.java
validation/src/main/java/io/micronaut/validation/validator/constraints/ConstraintValidatorContext.java
validation/src/test/groovy/io/micronaut/validation/validator/pojo/ContextValidationSpec.groovy

https://github.com/micronaut-projects/micronaut-core/issues/3243

Provide root bean in ConstraintValidatorContext

---

graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
inject/src/main/java/io/micronaut/inject/visitor/VisitorContext.java
src/main/docs/guide/languageSupport/graal.adoc
src/main/docs/guide/languageSupport/graal/graalServices.adoc

Improves #3108.
I've also updated the documentation to include GraalVM 20.1.0 which will be released today.

Generate resource-config.json

---

gradle.properties

Bump micronaut-kotlin to 1.0.0.RC3

---

build.gradle

The group has been changed: https://github.com/micronaut-projects/micronaut-micrometer/blob/master/build.gradle#L44

Update micronaut-micrometer groupId

---

core/src/main/java/io/micronaut/core/serialize/JdkSerializer.java
core/src/main/java/io/micronaut/core/serialize/ObjectSerializer.java
runtime/src/main/java/io/micronaut/jackson/serialize/JacksonObjectSerializer.java

To allow deserializing generic collections when using "@Cacheable".
I will add PR for Redis cache to call the new method.

ObjectSerializer should deserialize using Argument<T>

---

http-server/src/main/java/io/micronaut/http/server/context/ServerRequestContextFilter.java
tracing/src/test/groovy/io/micronaut/tracing/instrument/util/MDCSpec2.groovy

Allow propagating MDC values set in doFilter.

Clean MDC context 2

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/annotation/GroovyAnnotationMetadataBuilder.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/JavaAnnotationMetadataBuilder.java
inject-java/src/main/java/io/micronaut/annotation/processing/ServiceDescriptionProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/AbstractTypeElementSpec.groovy
inject-java/src/test/groovy/io/micronaut/inject/annotation/AnnotationMapperSpec.groovy
inject/src/main/java/io/micronaut/inject/annotation/AbstractAnnotationMetadataBuilder.java

Support @AliasFor in AnnotationMapper instances. 

---

src/main/docs/guide/httpServer/binding.adoc
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/MovieTicketBean.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/MovieTicketController.groovy
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/binding/MovieTicketControllerSpec.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/MovieTicketBean.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/MovieTicketController.kt
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/server/binding/MovieTicketControllerTest.kt
test-suite/src/test/java/io/micronaut/docs/server/binding/MovieTicketBean.java
test-suite/src/test/java/io/micronaut/docs/server/binding/MovieTicketController.java
test-suite/src/test/java/io/micronaut/docs/server/binding/MovieTicketControllerSpec.java

This PR adds documentation for @RequestBean.

Add documentation for @RequestBean

---

inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaMethodElement.java

- skip last method parameter if it is a Continuation
- Continuation holds the return type.

Handle kotlin coroutines

---

graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java
inject-java/src/main/java/io/micronaut/annotation/processing/TypeElementVisitorProcessor.java
inject/src/main/java/io/micronaut/inject/visitor/VisitorContext.java

Fixes #3274
After this is merged, merge https://github.com/micronaut-projects/micronaut-starter/pull/256

Use module/group if define for generated GraalVM files path.

---

jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java

Backported from https://github.com/micronaut-projects/micronaut-sql/pull/173

Support newer versions of SQL Server driver in GraalVM

---

http-netty/src/main/java/io/micronaut/http/netty/channel/converters/EpollChannelOptionFactory.java
http-netty/src/main/java/io/micronaut/http/netty/channel/converters/KQueueChannelOptionFactory.java
http-netty/src/main/java/io/micronaut/http/netty/graal/HttpNettyFeature.java

Related to #3252
Please note that I only made native-image build adding `--report-unsupported-elements-at-runtime`

Fix GraalVM warnings and support for Netty native transport

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/EpollEventLoopGroupFactory.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/KQueueEventLoopGroupFactory.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/NioEventLoopGroupFactory.java

required for https://github.com/micronaut-projects/micronaut-micrometer/pull/72

Turn EventLoopGroupFactories public

---

http-netty/src/main/java/io/micronaut/http/netty/channel/KQueueEventLoopGroupFactory.java

required for https://github.com/micronaut-projects/micronaut-micrometer/pull/72

Turn KQueueEventLoopGroupFactory public

---

src/main/docs/guide/httpClient/clientFilter.adoc
test-suite-groovy/src/test/groovy/io/micronaut/docs/client/filter/GoogleAuthFilter.groovy
test-suite-kotlin/src/test/kotlin/io/micronaut/docs/client/filter/GoogleAuthFilter.kt
test-suite/src/test/java/io/micronaut/docs/client/filter/GoogleAuthFilter.java
test-suite/src/test/java/io/micronaut/docs/client/filter/GoogleAuthFilterSpec.java

Document the need to use Provider to inject clients. 

---

runtime/src/main/java/io/micronaut/reactive/rxjava2/RxInstrumentedWrappers.java

This will change instrumentation to skip if previous one is already wrapped:
```
.just(value) -> wrap
.map ... -> skip
.filter... -> skip
```
```
externalSource 
.map ... -> wrap
.filter... -> skip
```

Reduce RxJava2 wrappers

---

src/main/docs/guide/introduction/upgrading.adoc

Explain the old Kubernetes discovery service deprecation

---

jdbc/src/main/java/io/micronaut/jdbc/nativeimage/JdbcFeature.java

Backported from https://github.com/micronaut-projects/micronaut-sql/pull/192

Add support for latest Postgresql driver in GraalVM

---

core/src/main/java/io/micronaut/core/io/file/DefaultFileSystemResourceLoader.java
inject/config/application.yml
inject/custom-config/application.yml
inject/src/main/java/io/micronaut/context/ApplicationContextBuilder.java
inject/src/main/java/io/micronaut/context/ApplicationContextConfiguration.java
inject/src/main/java/io/micronaut/context/DefaultApplicationContextBuilder.java
inject/src/main/java/io/micronaut/context/env/DefaultEnvironment.java
inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy
inject/src/test/resources/custom-config/application.yml

Not sure if it needs to be configured or it's fine to have it like this.

Support storing property files in config folder

---

build.gradle
gradle.properties

Give this one more go now that things are good to go when using the new build tools in micronaut-acme.

Adding micronaut-acme into bom at 1.0.0.RC3

---

validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
validation/src/test/groovy/io/micronaut/validation/ValidatedController.java
validation/src/test/groovy/io/micronaut/validation/ValidatedSpec.groovy

Fix validation of optional param

---

validation/src/main/java/io/micronaut/validation/validator/messages/DefaultValidationMessages.java
validation/src/test/groovy/io/micronaut/validation/validator/constraints/ConstraintMessagesSpec.groovy

Add default validation messages for @DecimalMin/Max

---

core/src/main/java/io/micronaut/core/io/scan/ClassPathAnnotationScanner.java

Reducing `java.io.File` usage might bring some performance improvements.

Reduce io.File usage

---

src/main/docs/guide/commandLineApps.adoc

Proposed better choice of word. Let me know your thoughts.

Edited commandLineApps.adoc

---

src/main/docs/guide/httpServer/serverConfiguration/https.adoc

https://github.com/micronaut-projects/micronaut-core/issues/3606

Add missing -chain operand for openssl command in https guide

---

http-client/src/main/java/io/micronaut/http/client/netty/RxNettyHttpClientRegistry.java
http-server-netty/build.gradle
http-server-netty/src/main/java/io/micronaut/http/server/netty/NettyHttpRequest.java
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
http-server-netty/src/test/groovy/io/micronaut/http/server/netty/http2/Http2PostTest.java
test-suite/src/test/groovy/io/micronaut/http/client/http2/Http2RequestSpec.groovy

Fix handling of HTTP content chunks. Fixes #3618

---

core/src/main/java/io/micronaut/core/convert/value/ConvertibleMultiValuesMap.java

Remove unreachable code

---

http/src/main/java/io/micronaut/http/uri/UriMatchTemplate.java
test-suite-groovy/src/test/groovy/io/micronaut/docs/server/uris/UriTemplateTest.groovy

Simply cutting off trailing slash to make it compatible with micronaut.

Match url with trailing slash

---

inject/src/main/java/io/micronaut/context/DefaultBeanContext.java

This change removes the use of computeIfAbsent which for some cases leads to recursive update.
There may be a slight cost in terms of duplicate initialization of BeanDefinition caches dependency on the injection path,
but I don't think it is worth the cost of tring to retain atomicity of computeIfAbsent since these are just the caches
for the backing bean definitions and not the bean instances themselves. We may even want to attempt a periodic purge
of these caches to save memory, but that is a separate issue.
I have not been able to come up with a test that replicates the issue, but have verified it fixes in the problem
by testing in the Micronaut Security code base. Once Security upgrades to 2.0.1 the intermittent failure should be fixed there.
Fixes #3577

Remove use of computeIfAbsent.

---

inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
inject/src/main/java/io/micronaut/inject/writer/AbstractClassFileWriter.java

Fix nested type arguments generation

---

src/main/docs/guide/appendix/breaks.adoc

document breaking change from micronaut 1.x to 2.x - LogLevel enum moved

---

http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
http-client/src/test/groovy/io/micronaut/http/client/retry/HttpClientRetrySpec.groovy

Fixes #3619
- Test for issue #3619
- Reset the body after encoding the request. Fixes #3619

Reset the body after encoding the request.

---

graal/src/main/java/io/micronaut/graal/reflect/GraalTypeElementVisitor.java

Fixes #3709
This PR supersedes https://github.com/micronaut-projects/micronaut-starter/pull/296

Add OpenAPI yml and UI to GraalVM resources if Swagger is present.

---

runtime/src/main/java/io/micronaut/runtime/converters/time/TimeConverterRegistrar.java
session/src/test/groovy/io/micronaut/session/http/HttpSessionConfigurationSpec.groovy

Add converter for TemporalAmount

---

src/main/docs/guide/configurations/dataAccess.adoc

Maven coordinates are : 
https://mvnrepository.com/artifact/io.micronaut.groovy/micronaut-hibernate-gorm
https://mvnrepository.com/artifact/io.micronaut.groovy/micronaut-mongo-gorm
https://mvnrepository.com/artifact/io.micronaut.groovy/micronaut-neo4j-gorm

doc: GORM maven group to io.micronaut.groovy

---

src/main/docs/guide/languageSupport/java/lombok.adoc

The configuration example for gradle is correct, but for the maven configuration the dependency declaration is missing. See the documentation here: https://projectlombok.org/setup/maven
When adding the dependency lombok works correctly in my project. 🙂

added missing lombok dependency for the maven configuration

---

core/src/main/java/io/micronaut/core/io/socket/SocketUtils.java

This reverts commit e89348a4700ba1930f80e757e36afb3e9dbd59ba.
It was discovered the change was incompatible with Windows

Revert "SocketUtils considers a port available if a ConnectException is thrown during connect attempt (#3670) (#3726)

---

http/src/main/java/io/micronaut/http/MutableHttpHeaders.java

See [Issue 3806](https://github.com/micronaut-projects/micronaut-core/issues/3806).

Issue 3806

---

inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java
inject/src/test/groovy/io/micronaut/context/env/PropertySourcePropertyResolverSpec.groovy

Resolves Issue / Bug: #3811 
Looks like an off by 1 error :). This PR sponsored by the letter A
Signed-off-by: Ken Sipe <kensipe@gmail.com>

PropertySourcePropertyResolver now resolves properties starting with A

---

core/src/main/java/io/micronaut/core/graal/AutomaticFeatureUtils.java

See https://github.com/micronaut-projects/micronaut-sql/issues/275
Once this is merged and Micronaut 2.0.2 released I will merge https://github.com/micronaut-projects/micronaut-sql/pull/278 with the changes.

Add new utility methods for GraalVM and refactor

---

runtime/src/main/java/io/micronaut/health/HeartbeatTask.java

Fixes https://github.com/micronaut-projects/micronaut-grpc/issues/33
The problem is that `HeartbeatTask` only allows to store one `ServiceInstance` so when the application uses Netty and gRPC, the second one that is registered wins (usually Netty), and overrides the first one. During bootstrap both ports are registered in Consul but after the first heartbeat is sent only one is sent and the other one is displayed as fail in Consul.
@graemerocher I'm not really sure if my fix using a `Set` backed by a `ConcurrentHashMap` is the way to go or not. I don't know the decission about using an `AtomicReference` in the first place but I think it may not be necessary because we only called the `get` method and not use any of `getAndSet`, `getAndUpdate`,...; also the `set` method in only called once …

Keep a collection of ServiceInstace to send a Heartbeat for all of them

---

build.gradle
gradle.properties

Add old Oracle driver coordinates to the BOM

---

inject/custom-config/application-env1.yml
inject/custom-config/application-env2.yml
inject/src/test/groovy/io/micronaut/context/env/DefaultEnvironmentSpec.groovy

Adds tests to DefaultEnvironmentSpec to validate assumptions about environment order with custom config locations

Adds tests to validate property loading with custom config locations and environment order

---

inject-java-test/src/main/groovy/io/micronaut/annotation/processing/test/AbstractTypeElementSpec.groovy
inject-java-test/src/test/groovy/io/micronaut/inject/visitor/beans/BeanIntrospectionSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/SuperclassAwareTypeVisitor.java
inject-java/src/main/java/io/micronaut/annotation/processing/visitor/JavaClassElement.java

Fix introspections on overridden methods in interfaces with generic return type

---

inject-java/src/test/groovy/io/micronaut/inject/property/FieldPropertyInject.java
inject-java/src/test/groovy/io/micronaut/inject/property/PropertyAnnotationSpec.groovy
inject/src/main/java/io/micronaut/context/env/PropertySourcePropertyResolver.java

Added support for maps with multiple values for property injection

---

core/src/main/java/io/micronaut/core/async/publisher/AsyncSingleResultPublisher.java
core/src/main/java/io/micronaut/core/async/publisher/CompletableFuturePublisher.java
core/src/main/java/io/micronaut/core/async/publisher/Publishers.java
http-client-core/src/main/java/io/micronaut/http/client/filters/ClientServerRequestTracingPublisher.java
http/src/main/java/io/micronaut/http/context/ServerRequestTracingPublisher.java
test-suite/src/test/groovy/io/micronaut/tracing/jaeger/HttpTracingSpec.groovy
tracing/src/main/java/io/micronaut/tracing/brave/instrument/http/HttpClientTracingPublisher.java
tracing/src/main/java/io/micronaut/tracing/brave/instrument/http/HttpServerTracingPublisher.java
tracing/src/main/java/io/micronaut/tracing/instrument/util/ScopePropagationPublisher.java
tracing/src/main/java/io/micronaut/tracing/instrument/util/TracingPublisher.java

Add marker interface to Micronaut publishers

---

http-client/src/main/java/io/micronaut/http/client/netty/DefaultHttpClient.java
http-netty/src/main/java/io/micronaut/http/netty/channel/ChannelPipelineCustomizer.java
test-suite/src/test/groovy/io/micronaut/docs/http/client/proxy/ProxyRequestSpec.groovy

Fix proxying of empty responses with proxy client. Fixes #3964

---

http-client/src/test/groovy/io/micronaut/http/client/NonMutableResponseSpec.groovy
http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java

Convert non mutable to mutable responses

---

validation/src/main/java/io/micronaut/validation/validator/DefaultValidator.java
validation/src/test/groovy/io/micronaut/validation/ValidatedController.java
validation/src/test/groovy/io/micronaut/validation/ValidatedSpec.groovy

Fix NPE with validating null wrapped values

---

http-server-netty/src/test/groovy/io/micronaut/http/server/netty/stream/JsonStreamSpec.groovy
runtime/src/main/java/io/micronaut/jackson/parser/JacksonProcessor.java

Fix EOF exception with empty json stream

---

http-server-netty/src/main/java/io/micronaut/http/server/netty/RoutingInBoundHandler.java
test-suite/src/test/groovy/io/micronaut/upload/PrincipalBinder.java
test-suite/src/test/groovy/io/micronaut/upload/PrincipalFilter.java
test-suite/src/test/groovy/io/micronaut/upload/StreamUploadSpec.groovy
test-suite/src/test/groovy/io/micronaut/upload/UploadController.java

Don't attempt to read the body if the body is already satisfied

---

inject-groovy/src/main/groovy/io/micronaut/ast/groovy/InjectTransform.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/Pojo.groovy
inject-groovy/src/test/groovy/io/micronaut/inject/configproperties/ValidatedConfigurationSpec.groovy
inject-java/src/main/java/io/micronaut/annotation/processing/BeanDefinitionInjectProcessor.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/Pojo.java
inject-java/src/test/groovy/io/micronaut/inject/configproperties/ValidatedConfigurationSpec.groovy
validation/src/test/groovy/io/micronaut/validation/validator/pojo/PojoConfigProps.java
validation/src/test/groovy/io/micronaut/validation/validator/pojo/PojoConfigurationPropertiesSpec.groovy

Ensure @Valid triggers bean definitions to be validatable

---

test-suite/src/test/java/io/micronaut/docs/client/filter/GoogleAuthFilterSpec.java

fixes: #4006

---

http-client/src/main/java/io/micronaut/http/client/netty/FullNettyClientHttpResponse.java
http-client/src/main/java/io/micronaut/http/client/netty/NettyStreamedHttpResponse.java
http-client/src/test/groovy/io/micronaut/http/client/netty/FullNettyClientHttpResponseSpec.groovy
http-client/src/test/groovy/io/micronaut/http/client/netty/NettyStreamedHttpResponseSpec.groovy
http-netty/src/main/java/io/micronaut/http/netty/cookies/NettyCookies.java
http-netty/src/test/groovy/io/micronaut/http/netty/cookies/NettyCookiesSpec.groovy
http/src/main/java/io/micronaut/http/HttpResponse.java
http/src/main/java/io/micronaut/http/bind/binders/QueryValueArgumentBinder.java

Add http cookies

---

management/src/main/java/io/micronaut/management/endpoint/health/HealthEndpoint.java
management/src/main/java/io/micronaut/management/health/indicator/HealthCheckType.java
management/src/main/java/io/micronaut/management/health/indicator/annotation/Liveness.java
management/src/main/java/io/micronaut/management/health/indicator/annotation/Readiness.java
management/src/main/java/io/micronaut/management/health/indicator/service/ServiceReadyHealthIndicator.java
management/src/test/groovy/io/micronaut/management/endpoint/EndpointsPortSpec.groovy
management/src/test/groovy/io/micronaut/management/endpoint/health/HealthEndpointSpec.groovy
src/main/docs/guide/introduction/whatsNew.adoc
src/main/docs/guide/management/providedEndpoints/healthEndpoint.adoc

Liveness and readiness probes
